<?php         
$this->title = "Editar usuario";
$this->headTitle($this->title);
?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Panel Principal</a></li>
    <li><a href="/admin/list">Usuario</a></li>
    <li class="active">Editar</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <div class="row">
        <div class="col-sm-12">
        <!-- EDIT FORM -->
            <form id="edit-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Editar</strong> Usuario</h3>
                    </div>

                    <div class="panel-body">
                    
                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Nombre</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="nombre" type="text" class="form-control" value="<?php echo $this->data['nombre'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Apellido</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="apellido" type="text" class="form-control" value="<?php echo $this->data['apellido'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                         <div class="form-group" id="form-group-marca" >
                            <label class="col-sm-3 col-xs-12 control-label">Administrador</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <input type="checkbox" name="administrador" id="administrador" <?php echo($this->data['administrador'] == 1) ? 'checked' : ''  ?> >
                                </div> 
                            </div>
                        </div>

                        <div class="text-center" id="user_image">
                            <img src="<?php echo $this->data['avatar_url'] ?>" class="img-thumbnail" width="200px">
                            <span class="help-block">Avatar actual</span>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Avatar</label>
                            <div class="col-sm-6 col-xs-12">               
                                <input name="avatar_url" type="file" class="fileinput btn-primary" title="Browse file"/>
                            </div>
                        </div>

                        <div class="form-group">                                        
                            <label class="col-sm-3 col-xs-12 control-label">Nueva contraseña</label>
                            <div class="col-sm-6 col-xs-12">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-unlock-alt"></span></span>
                                    <input name="password" type="password" class="form-control"/>
                                </div>
                                <span class="help-block">Dejar el campo "Nueva contraseña" en blanco para mantener la contraseña actual.</span>
                            </div> 
                        </div>
                        
                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-default" type="button" onclick="history.back()">Back</button>
                        <button class="btn btn-primary pull-right">Submit</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script src="/admin-public/js/bootstrap-switch.min.js"></script>
<!-- END THIS PAGE PLUGINS -->

<script>
$().ready(function() {
    $.fn.bootstrapSwitch.defaults.size = 'mini';
    $("[name='administrador']").bootstrapSwitch();

    $("#edit-form").validate({
        rules: {
            nombre: "required",
            apellido: "required",
            password: {
                minlength: 8
            }
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        }
    });
});
</script>