<?php         
$this->title = "Agregar nuevo producto del proveedor";
$this->headTitle($this->title);
?>
<!-- BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="/">Panel Principal</a></li>
        <li><a href="/productoproveedor/list">Producto Proveedor</a></li>
        <li class="active">Nuevo</li>
    </ul>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-sm-12">
        <!-- ADD FORM -->
            <form id="add-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Nuevo</strong> Producto</h3>
                        <ul class="panel-controls">
                        </ul>
                    </div>

                    <div class="panel-body">

                        <div class="form-group" >
                            <label class="col-sm-3 col-xs-12 control-label">Proveedor</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-suitcase"></span></span>
                                    <select name="id_proveedor" id="id_proveedor" type="text" class="form-control select">
                                        <option value="">Selecciona Proveedor</option>
                                        <?php 
                                           foreach ($this->listadoProveedores as $key => $proveedor): ?>
                                                <option <?php echo $this->data['id_proveedor'] == $proveedor['id'] ? "selected" : '' ; ?> value=<?php echo  $proveedor['id'] ?>><?php echo $proveedor['razon_social']?></option>
                                            
                                        <?php endforeach; ?>
                                    </select>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group" id="form-group-marca" >
                            <label class="col-sm-3 col-xs-12 control-label">Marca</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-suitcase"></span></span>
                                    <select name="id_marca" id="id_marca" type="text" class="form-control select">
                                        <option value="">Selecciona Marca</option>
                                        <?php 
                                           foreach ($this->listadoMarcas as $key => $marca): ?>
                                                <option <?php echo $this->data['id_marca'] == $marca['id'] ? "selected" : '' ; ?> value=<?php echo  $marca['id'] ?>><?php echo $marca['nombre']?></option>
                                            
                                        <?php endforeach; ?>
                                    </select>
                                </div> 
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Código producto proveedor</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="cod_proveedor" id="cod_proveedor" type="text" class="form-control"/>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Descripción</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="descripcion" id="descripcion" type="text" class="form-control"/>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Precio</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="precio" id="precio" type="text" class="form-control"/>
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Descuento</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="descuento" id="descuento" type="number" class="form-control"/>
                                </div>
                            </div>
                        </div>
                        <div class="form-group ">                                        
                            <label class="col-md-3 col-xs-12 control-label ">Fecha</label>
                            <div class="col-md-6 col-xs-12">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                    <input name="fecha" id="fecha" value="<?= $this->data['fecha']?>" type="text" class="form-control datepicker" />
                                </div>            
                            </div>
                        </div>

                        <!-- <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Fecha</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="fecha" id="fecha" type="date" class="form-control"/>
                                </div>
                            </div>
                        </div> -->
                        
                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-default" type="button" onclick="history.back()">Volver</button>
                        <button class="btn btn-primary pull-right">Guardar</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datepicker.js"></script> 
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-select.js"></script>   
<script type=“text/javascript” src=“/js/plugins/jquery-validation/jquery.validate.js”></script>
<!-- END THIS PAGE PLUGINS -->

<script>
$().ready(function() {
    $('#fecha').datepicker({
        format: "dd/mm/yyyy"
        
    });  
    $("#add-form").validate({
        ignore: '',
        rules: {
            id_proveedor: "required",
            codigo_proveedor: "required",
            descripcion: "required",
            id_marca: "required",
            fecha: "required",
            punto_pedido: "required"
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        messages: {

            id_proveedor: {
                required: "Campo requerido"
            },
            descripcion: {
                required: "Campo requerido"
            },
            id_marca: {
                required: "Campo requerido"
            },
            codigo_proveedor: {
                required: "Campo requerido"
            },
            precio: {
                required: "Campo requerido"
            },
            fecha: {
                required: "Campo requerido"
            }
        }
    });
});
 
</script>