<?php         
$this->title = "Nueva venta";
$this->headTitle($this->title);
?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Panel Principal</a></li>
    <li><a href="/venta/list">Venta</a></li>
    <li class="active">Nueva</li>
</ul>
<!-- END BREADCRUMB -->

<style>
.profile-controls .profile-control-left{display:none;}

</style>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <div class="row">
        <div class="col-md-12">

            <!-- START WIZARD WITH VALIDATION -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Nueva venta</h3>                                
                    <div class="wizard show-submit form-horizontal">
                        <ul>
                            <li>
                                <a href="#step-1" class="step-1">
                                    <span class="stepNumber">1</span>
                                    <span class="stepDesc">Seleccionar<br /><small>Cliente</small></span>
                                </a>
                            </li>

                            <li>
                                <a href="#step-2" class="step-2">
                                    <span class="stepNumber">2</span>
                                    <span class="stepDesc">Seleccionar<br /><small> Productos</small></span>
                                </a>
                            </li>
                            <li>
                                <a href="#step-3" class="step-3">
                                    <span class="stepNumber">6</span>
                                    <span class="stepDesc">Finalizar<br /><small>Venta</small></span>
                                </a>
                            </li>
                          
                        </ul>

                       
                        <div id="step-1">
                            <!-- START STRIPED TABLE SAMPLE -->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Clientes</h3>
                                    <div class="col-md-2" style="float:right;">
                                        <button class="btn btn-success btn-block">
                                            <a href="/cliente/add"><span class="fa fa-plus"></span> Nuevo</a>
                                        </button>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="panel-body">
                                        <p>Buscar cliente</p>
                                        <div class="col-md-6" style="padding-left:0px;">
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                    <span class="fa fa-search"></span>
                                                </div>
                                                <input id="patientsearch" name="search" type="text" class="form-control" placeholder="Buscar Cliente" value="<?= $this->patient; ?>"/>
                                                <div class="input-group-btn">
                                                    <button class="btn btn-primary btn-buscar-cliente">Buscar</button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3" style="padding-left:0px;padding-right:0px;padding-top:6px;width:110px;">
                                            <div class="result-search-patient"></div>
                                        </div>
                                        <div class="col-md-3" style="padding:0px;">
                                            <div class="input-group">
                                                <div class="col-md-12" style="position:relative;top:-9px;width:220px;">
                                                    <ul class="pagination pagination-sm pull-right push-down-10 push-up-10" style="width: 100%;display:none;">
                                                        <span id='back-patient' class='btn btn-default'>« anterior</span>
                                                        <span id='back-patient-disabled' class='btn btn-default' style='display:none;background-color: #DDD;cursor:no-drop;'>« anterior</span>
                                                        <span id='next-patient' class='btn btn-default'>siguiente »</span>
                                                        <span id='next-patient-disabled' class='btn btn-default' style='display:none;background-color: #DDD;cursor:no-drop;'>siguiente »</span>
                                                        <span class='pagination-data' style='position:relative;margin-left:5px;'></span>
                                                        <span id='page-patient' rel='1'></span>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="list-cliente" class="col-md-12">
                                    <?php if( count($this->clientes) == 0) : ?>
                                        <div class="col-md-12">
                                            <div class="panel panel-default">
                                                <div class="panel-body">
                                                    <p style="text-align:center;">Buscar cliente</p>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>

                            </div>
                            <!-- END STRIPED TABLE SAMPLE -->
                        </div>

                        <div id="step-2">

                            <!-- START STRIPED TABLE SAMPLE -->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 id="from_driver" class="panel-title">Productos</h3>
                                </div>
                                <div class="panel-body">
                                    <p>
                                        <div class="form-group">
                                            <div class="col-md-3">
                                                <input id="buscar-productos" class="form-control" placeholder="Buscar productos"/>
                                            </div>
                                            <div class="col-md-2">
                                                <button class="btn btn-buscar-producto"><i class="glyphicon glyphicon-search"></i></button>
                                            </div>
                                             <label class="col-md-2 control-label" style="width:auto; text-align:left;">Descuento</label>
                                            <div class="col-md-2">
                                                <label class="switch">
                                                  <input id="switch-descuento" type="checkbox" data-size="mini">
                                                  <span class="slider round"></span>
                                                </label>
                                            </div>
                                            <label class="col-md-2 control-label" style="width:auto; text-align:left;">Enviar</label>
                                            <div class="col-md-2">
                                                <label class="switch">
                                                  <input id="switch-envio" type="checkbox" data-size="mini">
                                                  <span class="slider round"></span>
                                                </label>
                                            </div>
                                        </div>
                                    </p>
                                    <div class="table-responsive products">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Código</th>
                                                    <th>Nombre</th>
                                                    <th>Marca</th>
                                                    <th>Stock</th>
                                                    <th>Precio ($)</th>
                                                    <th>Estado</th>
                                                    <th style="width: 70px">Acciones</th>
                                                <tr>
                                            </thead>
                                            <tbody id="productList"></tbody>
                                        </table>
                                    </div>
                                    <span id="prev" class="btn btn-default"> Anterior </span>
                                    <span id="next" class="btn btn-default"> Siguiente </span>
                                    <span id="page" rel="1"></span>
                                </div>
                            </div>
                            <!-- END STRIPED TABLE SAMPLE -->
                        </div>

                        <div id="step-3">
                            <!-- START STRIPED TABLE SAMPLE -->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Resumen de la venta</h3>
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Coupon</label>
                                        <span id="couponspan">
                                            <strong id="couponamount"><span class="fa fa-ticket" style="float:none;color: #719D47;"></span></strong>
                                        </span>  
                                        <div class="col-md-6">
                                            <input id="coupon_value" type="text" class="form-control">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <h6 style="text-align: center"><u>Reward Discount</u></h6>  
                                        <div class="col-md-12" style="text-align: center;">
                                         <h3><span id="rdiscount">0%</span></h3>
                                          <input id="rdiscount_hidden" type="hidden" class="form-control" value="0">                       
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Discount</label>
                                       
                                        <div class="col-md-3 " id="percent_fa">
                                              
                                            <select class="form-control select" id="discount_options">
                                                <option value="select_discount"><?php echo "Please select a discount" ?></option>
                                                <?php foreach ($this->discount as $i => $discount) {?> 
                                                <option value="<?php echo $discount['id_discount']; ?>" attr-amount="<?php echo $discount['amount']; ?>" attr-reason ="<?php echo $discount['reason']; ?>"> <?php echo $discount['name']; ?></option>
                                                <?php } ?> 
                                            </select>
                                        </div>
                                        <div class="input-group col-md-2">
                                            <input id="discount" name="discount" value="0" type="text" class="form-control" style="border-radius: 4px !important;" readonly>
                                            
                                        <span class="fa fa-question-circle fa-lg col-md-1 qstdon" aria-hidden="true" data-toggle="tooltip" title="Write a number to set the discount in a specific amount, or type '%' after the number to set it as a percentage"></span> 
                                        </div> 
                                        <div class="form-group" style="display:none" id="reason">
                                            <label class="col-md-3 control-label">Reason</label>
                                            <div class="col-md-6">
                                                <textarea class="form-control" name="reason" id="reason_value" ></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                          <!--   <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Fees</h3>
                                </div>
                                <div class="panel-body">
                                    
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Shipping</label>
                                        <div class="input-group col-md-3">
                                            <div class="input-group-addon">
                                                <span class="fa fa-truck"></span>
                                            </div>
                                            <input id="shipping" name="shipping" type="number" class="form-control" value="0" min="0" style="border-radius: 4px !important;">
                                            <input id="discount_hidden" type="hidden" class="form-control" value="0">
                                            <span class="fa fa-question-circle fa-lg col-md-1 qstdon" aria-hidden="true" data-toggle="tooltip" title="Add a surcharge for shipping concepts"></span> 
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Convenience</label>
                                        <div class="input-group col-md-3">
                                            <div class="input-group-addon">
                                                <span class="fa fa-money"></span>
                                            </div>
                                            <input id="convenience" name="convenience" type="number" class="form-control" value="0" min="0" style="border-radius: 4px !important;">
                                            <input id="discount_hidden" type="hidden" class="form-control" value="0"> 
                                            <span class="fa fa-question-circle fa-lg col-md-1 qstdon" aria-hidden="true" data-toggle="tooltip" title="Add a surcharge for particular concepts"></span>
                                        </div> 
                                    </div>
                                                                   
                                </div>
                            </div> -->
                            
                        </div>
                      
                        <div id="summary">
                            <!-- START STRIPED TABLE SAMPLE -->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Resumen</h3>
                                </div>
                                <div class="panel-body">
                                    <form id="crear-venta" role="form" class="form-horizontal">
                                        <input type="hidden" id="form-cliente" name="id_cliente">
                                        <input type="hidden" id="form-descuento" name="descuento">
                                        <input type="hidden" id="form-direccion" name="direccion">
                                        <input type="hidden" id="form-cuit" name="cuit">
                                        <input type="hidden" id="form-telefono" name="telefono">
                                        <input type="hidden" id="form-nombre" name="nombre">
                                        <input type="hidden" id="form-apellido" name="apellido">
                                        <input type="hidden" id="form-email" name="email">
                                        <input type="hidden" id="form-tipo_cliente" name="tipo_cliente">

                                        <!-- <input type="hidden" id="form-location" name="id_location"> -->
                                        <!-- <input type="hidden" id="form-time" name="time"> -->
                                        <!-- <input type="hidden" id="form-timeset" name="timeset"> -->
                                        <!-- <input type="hidden" id="form-donation_note" name="donation_note"> -->
                                        <!-- <input type="hidden" id="form-points" name="points"> -->
                                        <!-- <input type="hidden" id="form-id_discount" name="id_discount"> -->
                                        <!-- <input type="hidden" id="form-reason" name="reason"> -->
                                        <!-- <input type="hidden" id="form-special-discount" name="special-discount"> -->
                                        <!-- <input type="hidden" id="form-coupon" name="id_coupon"> -->
                                        <!-- <input type="hidden" id="form-discount" name="discount"> -->
                                        <!-- <input type="hidden" id="form-future_deliveries" name="future_deliveries"> -->
                                        <ul style="padding:0px;">
                                            <li class="fa fa-square-o">
                                                <span class="stepDesc">Cliente seleccionado: <span id="cliente-seleccionado"></span> </span>
                                            </li>
                                            <!-- <li class="fa fa-square-o">
                                                <span id="selected-phone" class="stepDesc">Productos seleccionados: </span>
                                            </li> -->
                                            <li id="selected-products" class="fa fa-square-o">
                                                <span class="stepDesc">Productos seleccionados:</span>
                                                <div class="table-responsive" style="margin-top:10px;">
                                                    <table class="table table-striped" style="font-size: 10px;display:none;">
                                                        <thead>
                                                            <tr>
                                                                <th>Cant</th>
                                                                <th>Código</th>
                                                                <th>Marca</th>
                                                                <th>Sub-Total</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                        </tbody>
                                                    </table>
                                                </div>
                                               <!--  <?php if(!empty($this->tax)): ?>
                                             
                                                <input type="checkbox" id="tax_exempt_checkbox" name="tax_exempt" style="display:none">
                                                <span id="tax_exempt"></span>
                                                <span id="tax" class="label label-warning label-form fee" style="width: 100%;"></span>
                                                <?php endif; ?> -->
                                                <span id="total_dona" class="label label-warning label-form fee" style="width: 100%;"></span>
                                                
                                                <span id="total_cost" class="label label-warning label-form fee" style="width: 100%;"></span>
                                                <input id="total_cost_hidden" name="total" type="hidden" value="0">
                                                <input id="subtotal_cost_hidden" name="subtotal_products" type="hidden" value="0">
                                                <span id="tot_discount" class="label label-default label-form tot_discount" style="width: 100%;"></span>
                                                <span id="tot_iva" class="label label-danger label-form tot_iva" style="width: 100%;"></span>
                                                <span id="envio" class="label label-primary label-form" style="width: 100%;"></span>
                                                <span id="tot_donation" class="label label-success label-form tot_donation" style="width: 100%;"></span>
                                                <input id="tax_hidden" name="tax" type="hidden" value="0">
                                                <input id="fee_shipping" name="fee_shipping" type="hidden" value="0">
                                                <input id="fee_convenience" name="fee_convenience" type="hidden" value="0">
                                                 
                                            </li>
                                            <li class="fa fa-square-o">
                                                <span id="form-total" class="stepDesc">Total: </span>
                                            </li>
                                            <!-- <li class="fa fa-square-o">
                                                <span id="selected-driver" class="stepDesc">Selected Driver: </span>
                                            </li> -->
                                            
                                            <!-- <li class="fa fa-square-o">
                                                <span id="selected-time" class="stepDesc">Selected Time: </span>
                                            </li> -->
                                        </ul>
                                    </form>
                                </div>
                            </div>
                            <!-- <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 id="previously_ordered" class="panel-title">Previously Ordered</br></h3>
                                </div>
                                <div id='previously_product_name'>

                                </div>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>                        
            <!-- END WIZARD WITH VALIDATION -->
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                
<div id="spinner">        
</div>
<!-- MODALS -->
<!-- <div class="modal" id="modal_add_phone" tabindex="-1" role="dialog" aria-labelledby="defModalHead" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="smallModalHead">Create new phone number</h4>
            </div>
            <form id="addphone-modal-form" class="form-horizontal" action="/admin_patients/addphoneajax" method="post" enctype="multipart/form-data" novalidate="novalidate">
                <div class="modal-body form-horizontal form-group-separated">                        
                    <div class="form-group">
                        <label class="col-md-3 control-label">Phone number</label>
                        <div class="col-md-9">
                            <input name="id_patient" id="id_patient" type="hidden" class="form-control">
                            <input name="number" id="number" type="text" class="form-control" placeholder="Enter the phone number">
                        </div>
                    </div>
                  
                </div>
                <div class="modal-footer">
                    <button id="save-add" type="button" class="btn btn-success">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div> -->
<!-- END MODALS -->

<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/moment.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datetimepicker.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-select.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/tagsinput/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin-public/js/additional-methods.min.js"></script>
<!-- END THIS PAGE PLUGINS -->

<!-- THIS PAGE PLUGINS -->    
<script type='text/javascript' src='/admin-public/js/plugins/icheck/icheck.min.js'></script>
<script type="text/javascript" src="/admin-public/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/owl/owl.carousel.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/smartwizard/jquery.smartWizard-3.3.1.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/jquery-validation/jquery.validate.js"></script>
<script src="https://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
<!-- <script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-slider.js"></script> -->
<!-- END PAGE PLUGINS -->

<script>

$('.datepicker').datepicker({
         format: 'dd-mm-yyyy'       
});

$(document).ready(function(){
    var  descuento;
    $('#switch-descuento').val(false);
    $('#switch-envio').val(false);

    $(document).on('change','#switch-descuento' ,function(e) {
        if(this.checked) $('#switch-descuento').val(true);
        else $('#switch-descuento').val(false);
        calculateTotal();
    });

    $(document).on('change','#switch-envio' ,function(e) {
        if(this.checked) $('#switch-envio').val(true);
        else $('#switch-envio').val(false);
        calculateTotal();
    });
     
     

    <?php if ( isset($this->patient) ) : ?>
    setTimeout(function(){
      $('.btn-buscar-cliente').click();
    }, 100);
    <?php endif; ?>


    $('#patientsearch').focus();

    $(".btn.btn-primary.pull-right").click(function(e){
        e.preventDefault();
        var params = $("#add-form").serialize();
        var action = $("#add-form").attr("action");
        result = panelAjax(action,params, function(data){
            if(data == true)
                 window.location.href = "/admin_donations";
        });
    });    

    $(".actionBar").insertBefore(".stepContainer")

    $('#discount_options').on('change', function(){
        var reason = $('option:selected', this).attr('attr-reason');
        var amount = $('option:selected', this).attr('attr-amount');       
        if(reason==1){
            $('#reason').show();
            $('#reason').css("display", "block");
            $('#discount').attr('readonly', false);
            $('#discount').val();
        }else{
            $('#reason').hide();
            $('#reason').css("display", "none");
            $('#discount').val(amount);
            $('#discount').attr('readonly', true);
            $('#reason_value').text('');
        }      
        $("#discount").trigger("keyup");     
    }); 
});

$(function() {
    var id_patient;
    var patient_dispenser;
    var id_location;
    var id_phone;
    var id_driver;
    var arrival_time;
    var latitude;
    var longitude;
    var products = new Array();
    var prices = {};
    var time;
    var is_ordered = false;

    //Click en finalizar
    $(".actionBar .buttonFinish").click(function(e){
        if(!validateSteps("6")) return; 
        if (!$(".actionBar .buttonFinish").hasClass("buttonDisabled")){
            $(".buttonFinish").fadeOut(50,function(){
                $("#form-donation_note").val($("textarea#donation_note").val());      
                // $("#form-id_discount").val($("#discount_options").val());  
                $("#form-reason").val($("#reason_value").val());  
                $("#form-discount").val($("#rdiscount_hidden").val());  
                $('#form-future_deliveries').val(futureDeliveries);
                
                var reason = $('#discount_options option:selected').attr('attr-reason');
                
                if (reason==1) {
                    if ($('#discount').val().includes("%")) {
                        discount = parseFloat($('#discount').val());
                    } 
                    else{
                        var total = parseFloat($("#subtotal_cost_hidden").val());
                        console.log(total);
                        disc = $('#discount').val();
                        discount = disc * 100 / total;
                    }             

                    $("#form-special-discount").val(discount); 

                }
                
                var params = {};

                params.data = $("#crear-venta").serialize();    
                params.futureDeliveries = futureDeliveries;
                panelAjax("/admin_donations/setdonation",params, function(data){              
 
                    if(data){
                        if(is_ordered){                          
                            updateTimeDonations();                           
                        }
                        else{
                            setTimeout(function(){ window.location.href = "/admin_donations"; }, 2000);                               
                        }
                   }else{
                        $(".buttonFinish").fadeIn();
                        $(".btn.btn-default.btn-lg.pull-right.mb-control-close").click();
                    }
                });
            });
            // Armo el Popup
            $("#message-box-warning").children(".mb-container").children(".mb-middle").children(".mb-title").html("Please wait");
            $("#message-box-warning").children(".mb-container").children(".mb-middle").children(".mb-content").html("<p>The system is setting the new donation.</p>");
            $("#message-box-warning").children(".mb-container").children(".mb-middle").children(".mb-footer").children(".mb-control-close").hide();

            setInterval(function() {
                $("#message-box-warning").children(".mb-container").children(".mb-middle").children(".mb-footer").children(".mb-control-close").fadeIn(500);
            }, 8000); // 8 segundos

            // Start Popup
            $(".btn.btn-warning.mb-control").click();
            // End Popup
        }
    
    });

    $(".actionBar .btn-default.pull-right").addClass("disabled");

    // $(".note_step5").append('<textarea data-toggle="tooltip" title="Limit 140 characters!" maxlength="140" name="note_donation" id="donation_note" class="form-control" placeholder="Type a note for this donation">');


    //Selecciono el cliente
    $("#list-cliente").on( "click", ".select-patient", function(slideEvt) {
        if($(this).attr('id') != ""){

            var params = {};
            params.direccion = $(this).find('.profile-data-direccion').text();
            params.tipo_cliente = $(this).find('.profile-data-tipo_cliente').text();
            params.telefono = $(this).find('.profile-data-telefono').text();
            params.email = $(this).find('.profile-data-email').text();
            params.cuit = $(this).find('.profile-data-cuit').text();
            params.descuento = $(this).find('.profile-data-descuento').text();
            params.id = $(this).attr('id');
            params.nombre = $(this).attr('title');

            $(this).toggleClass('selected');
            $(this).siblings().removeClass('selected');
              if(!$("#cliente-seleccionado").closest('li').hasClass("fa-check-square-o"))
                $("#cliente-seleccionado").closest('li').toggleClass('fa-square-o fa-check-square-o');
            $("#cliente-seleccionado").text(params.nombre);

            //lleno el formulario con datos del cliente
            $("#form-cliente").val(params.id);
            $("#form-descuento").val(params.descuento);
            $("#form-direccion").val(params.direccion);
            $("#form-cuit").val(params.cuit);
            $("#form-telefono").val(params.telefono);
            $("#form-nombre").val(params.nombre);
            $("#form-email").val(params.email);
            $("#form-tipo_cliente").val(params.tipo_cliente);
            $('.buttonNext').click();

            descuento = params.descuento;

             // Borrar los datos de los pasos siguientes
            resetForm(1);
            products = [];
            prices = {};       
            totalSum(prices);
            
        }else{
            if(!$(".actionBar .btn-default.pull-right").hasClass("disabled"))
                $(".actionBar .btn-default.pull-right").addClass("disabled");
        }
    });
    
    //Click para seleccionar el producto
    $(".products tbody").on( "click", "tr .select-product", function() {
        // Add Product
        producto_id = $(this).closest("tr").find("#id").text();
        producto_codigo = $(this).closest("tr").find("#codigo").text();
        producto_marca = $(this).closest("tr").find("#marca").text();
        producto_precio = $(this).closest("tr").find("#precio").text();
        producto_imagen = $(this).closest("tr").find("#imagen_url").text();
       
        if(jQuery.inArray( producto_id, products ) >= 0){
            alert("El producto ya se encuentra agregado");
            return;
        }
        $("#selected-products").removeClass("fa-square-o");
        $("#selected-products").addClass("fa-check-square-o");
        products.push(producto_id);
        prices[producto_id] = producto_precio;
        $("#selected-products table tbody").append('<tr>'+
                                                        '<input name="id_product[]" type="hidden" value="'+producto_id+'">'+
                                                        '<input name="price[]" type="hidden" value="'+producto_precio+'">'+
                                                        '<input name="subtotal[]" type="hidden" value="'+producto_precio+'">'+
                                                        // '<input name="gift[]" type="hidden" value="0">'+
                                                        // '<td><input name="cant[]" value="1" aria-invalid="false" class="valid quantity"></td>'+
                                                        '<td>'+producto_codigo+'</td>'+
                                                        '<td>'+producto_marca+'</td>'+
                                                        '<td>$'+producto_precio+'</td>'+
                                                        '<th><span class="fa fa-trash-o"></span></th>'+
                                             '</tr>');

        totalSum(prices);
        $("#selected-products table").show();
        $("#total_cost").show();
        $("#tot_donation").show();
        $("#tot_discount").show();
        $("#tot_iva").show();
        $("#envio").show();
        $("#tax_exempt_checkbox").show();
        $("#tax_exempt").html("Tax Exempt");
    });

    $("#selected-products tbody").on( "click", "tr .fa-trash-o", function() {
        // Remove Product
        id_producto = $(this).closest("tr").find("input[name='id_product[]']").val();
        index = products.indexOf(id_producto);
        products.splice(index, 1);
        delete prices[id_producto];
        $(this).closest("tr").remove();
        totalSum(prices);
    });

    $("#selected-products tbody").on( "change", "tr .quantity", function() {
        // Actualizar precio segun cantidad
        var product_tr = $(this).closest("tr");
        id_producto = $(this).closest("tr").find("input[name='id_product[]']").val();
        cant = $(this).val();
        if(cant<=0){
            $(this).val(1);
            $(this).attr('value',1);
            alert("La cantidad no puede ser cero o menos");
            return;
        }
        // if($(this).closest("tr").find("input[name='gift[]']").val() == "1") return;
        checkTierPrice(id_producto,cant,function(data){
            product_tr.find("input[name='subtotal[]']").val(data);
            prices[id_producto] = data;
            totalSum(prices);
        });
    });

    var timeoutID = null;
    $('#buscar-productos').keyup(function() {
        clearTimeout(timeoutID);
        var $target = $(this);
        var id_driver = $("#form-driver").val();
        var id_cliente = $("#form-cliente").val();
        timeoutID = setTimeout(function() { getProducts(); }, 500); 
    });

    $('#patientsearch').keyup(function(event) {
        var search = $('#patientsearch').val();
        if(search.length > 3 || event.keyCode == 13){
            clearTimeout(timeoutID);
            timeoutID = setTimeout(function() { getClientes(search); }, 500);
        }
    });

    $('.btn-buscar-producto').click(function() {
        getProducts();
    });

    $('.btn-buscar-cliente').click(function() {
        var search = $('#patientsearch').val();
        getClientes(search);
    });

    // $(".actionBar .btn-default.pull-right").click(function(){
    //     if($(".steps_5 .step-1").hasClass("selected"))
    //         $(".actionBar .btn-default.pull-right").addClass("disabled");
    // });

    $("#next").click(function() {
        var val     = $('#page').attr('rel');
        val         = parseInt(val) + parseInt(1);
        page        = $('#page').attr('rel',val);
        search      = $('#buscar-productos').val();
        id_cliente  = $("#form-cliente").val();
        getProducts();
    });

    $("#prev").click(function() {
        var val     = $('#page').attr('rel');
        if (val > 1) {
            val         = parseInt(val) - parseInt(1);
            page        = $('#page').attr('rel',val);
            search      = $('#buscar-productos').val();
            id_cliente  = $("#form-cliente").val();

            getProducts();
        }
    });


    var donations = [];
    var sortedDonations = [];
    var orderDonations = [];
    var datadonation = {};

    $("#sortable").before($("#sortable :first-child"));

    $("#sortable").sortable({ 
        placeholder: "ui-sortable-placeholder",
        items: 'li:not(:first)',
        start: function(event, ui) {
              ui.item.data('start_pos', ui.item.index());
        },
        stop: function(event, ui) {  
            var start_pos = ui.item.data('start_pos');
            if (start_pos != ui.item.index()) {
                is_ordered = true;
                orderDonations = [];           
                donations = [];
                $("#sortable li").each(function(i){
                     id_donation = $(this).attr("id"); 
                    $("#"+id_donation+" #diff").html("");
                    if(id_donation) donations.push(id_donation);
                    text = $(this).context.innerHTML;
                    orderDonations.push(text.substring(text.lastIndexOf("(")+1,text.lastIndexOf(")")));
                });
                var params = {};         
                params.donations = donations;
                params.datadonation = datadonation;
                params.id_driver = $('#form-driver').val();
                panelAjaxNoMessage("/admin_donations/getnewallowedtime",params, function(data){

                    $.each(data.diff,function(i,v){
                        $("#"+v.id_donation+" #diff").html(" ( "+v.difference+" M )");
                        sortedDonations[i] = {
                            id_donation : v.id_donation,
                            arrival_time : v.arrival_time_new
                        };

                        if(v.id_donation == "new"){
                            $.each(v.range,function(index,rangetime){
                                if(rangetime.status){
                                    $("#selected-time small").remove();
                                    $("#selected-time").append('<small> '+rangetime[0]+' - '+rangetime[1]+'</small>');
                                    $(".times .list-group .system-selected").removeClass("system-selected active");
                                    $('.times .list-group-item:contains('+rangetime[0]+' - '+rangetime[1]+')').remove();
                                    $('.times i').contents().first().remove();
                                    $('.times .list-group .ordertime').remove();
                                    $(".times .list-group").prepend('<a href="javascript:void(0);" class="list-group-item system-selected active ordertime">'+rangetime[0]+' - '+rangetime[1]+' <i>Selected by system as the best option</i></a>');
                                };
                            });
                            $(".times .list-group").append('<a href="javascript:void(0);" class="list-group-item">Overtime</a>');
                        };
                    }); 
                       
                });
                updateRoute();                                     
            }
        }       
    });

    $( "#sortable" ).disableSelection();

    var coupon = {};

    $('#discount').keyup(function(){
        var discount = $(this).val();

        var total = parseFloat($("#subtotal_cost_hidden").val());
        var percent = 0;
        if(discount.indexOf('%') > -1){
            percent = discount;
        }else{
            if(total){
                percent = discount * 100 / total;
            }
        }    
        $('#discount_hidden').val(percent);
        calculateDiscount();
        calculateTotal();
    });

    $('#shipping').change(function(){
        var shipping = $(this).val();
        calculateTotal();
    });

    $('#convenience').change(function(){
        var convenience = $(this).val();
        
        calculateTotal();
    });

    $('#selected-products').on('change','#tax_exempt_checkbox', function(){
        totalSum(prices);
    });

    var calculateDiscount = function(){
        var percent = 0;
        var total = parseFloat($("#subtotal_cost_hidden").val());
        if(!jQuery.isEmptyObject(coupon)){

            if(coupon.type == 'fix'){
                if(total)
                    percent = coupon.discount * 100 / total;    

            }else{
                percent = coupon.discount;
                // percent = coupon.discount * ((100 - percent) / 100) + percent
            }
        }
        if($('#reedemamount').text() != 0){
            if(total)             

                percentpoints = parseFloat($('#reedemamount').text()) * 100 / total;
                percent = percentpoints + percent;         
        }
        if($('#discount').val() != 0){
            if(total){  
                if ($('#discount').val().includes("%")) {
                    discount = parseFloat($('#discount').val());
                    percent = discount + percent;                                   
                } 
                else{
                    disc = parseFloat($('#discount').val());
                    discount = disc * 100 / total;
                    percent = discount  + percent; 
                }             
            }
        }
            total = (100 - percent) * total / 100;                  


        percent = percent ? percent.toFixed(2) : 0;
        $('#rdiscount').text(percent+'%');
        $('#rdiscount_hidden').val(percent);  
          
    }    

    var stepDisplay;

    function showSteps(directionResult) {
        // For each step, place a marker, and add the text to the marker's
        // info window. Also attach the marker to an array so we
        // can keep track of it and remove it when calculating new
        // routes.

        var myRoute = directionResult;
        var icon;
        var marker;
        for (var i = 0; i < myRoute.request.waypoints.length  ; i++) {
          if(orderDonations[i+1] == "⚑") icon = "https://chart.googleapis.com/chart?chst=d_map_pin_icon&chld=flag|ADDE63"
          else icon = "https://chart.googleapis.com/chart?chst=d_map_pin_letter&chld=" + orderDonations[i+1] + "|FF0000|000000";
          if(jQuery.isEmptyObject(orderDonations)) icon = "https://chart.googleapis.com/chart?chst=d_map_pin_letter&chld=" + (i + 2) + "|FF0000|000000";
          locationLatLng = myRoute.request.waypoints[i].location.split(',');
          marker = new google.maps.Marker({
            position: new google.maps.LatLng(locationLatLng[0],locationLatLng[1]), 
            map: mapDonation,
            icon: icon 
              
          }); 
          markerArray.push(marker);
        };

        marker = new google.maps.Marker({
          position: myRoute.request.origin, 
          map: mapDonation,
          icon:  "https://chart.googleapis.com/chart?chst=d_map_pin_letter&chld=1|FF0000|000000"
         
        });
        markerArray.push(marker);
        if(orderDonations[i+1] == "⚑") icon = "https://chart.googleapis.com/chart?chst=d_map_pin_icon&chld=flag|ADDE63"
        else icon = "https://chart.googleapis.com/chart?chst=d_map_pin_letter&chld=" + orderDonations[i+1] + "|FF0000|000000";
        if(jQuery.isEmptyObject(orderDonations)) icon = "https://chart.googleapis.com/chart?chst=d_map_pin_icon&chld=flag|ADDE63";
        
        marker = new google.maps.Marker({
          position: myRoute.request.destination, 
          map: mapDonation,
          icon: icon 
        });
        markerArray.push(marker);
        
        google.maps.event.trigger(markerArray[0], "click");      

      }
});


var totalSum = function(prices){
    var total_cost = 0;
    
    $.each(prices, function( index, value ) {
        total_cost = parseFloat(total_cost) + parseFloat(value);
    });
    tax = <?= json_encode($this->tax) ?>;
    tax = (total_cost * tax / 100);

    if(tax){
        if ($('#tax_exempt_checkbox').is(':checked')) {tax = 0;}

        $("#tax").html("<span style='float:left'>Tax:</span><span style='float:right;padding-right: 22px;'>$"+tax.toFixed(2)+"</span>");        
    };
   
    $('#subtotal_cost_hidden').val(total_cost.toFixed(2));
    total_cost = total_cost + tax;
    $("#tax_hidden").val(tax.toFixed(2));
    $("#total_cost").html("<span style='float:left'>Sub-Total:</span><span style='float:right;padding-right: 22px;'>$"+total_cost.toFixed(2)+"</span>");
    $("#total_cost_hidden").val(total_cost.toFixed(2));
    calculateTotal();
}

function validateSteps(step) {
    var status = true;
    var form_data = {};
    form_data = $("#crear-venta").serializeArray();
    switch(step) {
        case "1":
        console.log(form_data);

            if( form_data[0]['value']=="" ){
                status = false;
                $('.wizard').smartWizard('showMessage','Selecciona un cliente y haga click en "Siguiente".');
                $('.wizard').smartWizard('setError',{stepnum:step,iserror:true});
            }else{
                $('.wizard').smartWizard('hideMessage');
                $('.wizard').smartWizard('setError',{stepnum:step,iserror:false});
            }
            break;
        case "2":
            if( form_data[1]['value']=="" ){
                status = false;
                $('.wizard').smartWizard('showMessage','Selecciona los productos y haga click en "Siguiente".');
                $('.wizard').smartWizard('setError',{stepnum:step,iserror:true});         
            }else{
                $('.wizard').smartWizard('hideMessage');
                $('.wizard').smartWizard('setError',{stepnum:step,iserror:false});
            }
            break;
        case "3":
            if( form_data[2]['value']=="" ){
                status = false;
                $('.wizard').smartWizard('showMessage','Verifique los datos y haga click en "Finalizar".');
                $('.wizard').smartWizard('setError',{stepnum:step,iserror:true});         
            }else{
                $('.wizard').smartWizard('hideMessage');
                $('.wizard').smartWizard('setError',{stepnum:step,iserror:false});
            }
            break;
        // case "4":
        //     if( form_data[3]['value']=="" ){
        //         status = false; 
        //         $('.wizard').smartWizard('showMessage','Please choose driver and click next.');
        //         $('.wizard').smartWizard('setError',{stepnum:step,iserror:true});         
        //     }else{
        //         $('.wizard').smartWizard('hideMessage');
        //         $('.wizard').smartWizard('setError',{stepnum:step,iserror:false});
        //     }
        //     break;

        // case "6":
        //     if ($('#reason').css('display')=='block' && $("#reason_value").val() == '' || ($('#datetimepicker1 input').val() =='' && $('#enable_datetimepicker').is(':checked'))) {
        //         status = false; 
        //         if ($('#reason').css('display')=='block' && $("#reason_value").val() == '') {
        //             $('.wizard').smartWizard('showMessage','Please write the discount reason and click finish.');
        //             $('.wizard').smartWizard('setError',{stepnum:step,iserror:true});
        //         }else{
                    
        //             $('.wizard').smartWizard('showMessage','Please insert a date.');
        //             $('.wizard').smartWizard('setError',{stepnum:step,iserror:true});
        //         }
                         
        //     }else{
        //         $('.wizard').smartWizard('hideMessage');
        //         $('.wizard').smartWizard('setError',{stepnum:step,iserror:false});
        //     }
        //     break;       
        default:
            status = true;
            break;
    }

    return status;
}


function resetForm(step){
    if (step==1) {
        $("#form-location").val('');
        $("#form-total").parent().removeClass('fa-check-square-o');
        $("#form-total").parent().addClass('fa-square-o');
        $("#form-total").html('Total: ');
        $("#form-driver").val('');
        $("#selected-driver").parent().removeClass('fa-check-square-o');
        $("#selected-driver").parent().addClass('fa-square-o');
        $("#selected-driver").html('Selected Driver: ');
         $(".drivers .widget").removeClass("widget-success");
        // $("#form-phone").val('');
        // $("#selected-phone").parent().removeClass('fa-check-square-o');
        // $("#selected-phone").parent().addClass('fa-square-o');
        // $("#selected-phone").html('Selected Phone: ');
        $("#selected-products table tbody").empty();          
        $("#selected-products").removeClass("fa-check-square-o");
        $("#selected-products").addClass("fa-square-o");
        $("#selected-products table").hide();
        $("#tax_exempt_checkbox").hide();
        $("#total_cost").hide();
        $("#envio").hide();
        $("#tot_discount").hide();
        $("#tot_iva").hide();
        $("#tot_donation").hide();
        // $("#donation_note").val('');
        // $("#form-donation_note").val(''); 
        // $("#selected-time").closest("li").addClass("fa-square-o");
        // $("#selected-time").closest("li").removeClass("fa-check-square-o");
        // $("#selected-time small").remove();
        // $("#form-time").val('');
        // $("#form-timeset").val('');
        // $("#form-coupon").val('');
        // $("#form-points").val('');
        $("#discount").val('');
        $("#rdiscount").val('');
        $("#discount_hidden").val(0);
        $("#rdiscount_hidden").val(0);
        $("#discount").val(0);
        $("#form-discount").val('');      
    };
    if (step==3) {
        $("#step-3").find(".selected").html('<span class="label label-default label-form"></span>');
    };

    if (step==4) {
        $("#step-3").find(".selected").html('<span class="label label-default label-form"></span>');
    };
}

//Obtengo los productos parael PASO 2
function getProducts(){
    var params = {};
    params.search        = $('#buscar-productos').val();;
    params.page          = $('#page').attr('rel');
    if (params.page < 0) { params.page = 1; };

    panelAjax("/producto/getproductos/",params, function(data){
        $(".products tbody").html('');
        $.each(data.productos, function( index, value ){
            item = "<tr id='id_producto' value='"+ value.id +"'>" +
                "<td id='id' class='hidden'>" + value.id + "</td>" +
                "<td id='codigo'>" + value.codigo + "</td>" +
                "<td id='nombre'>" + value.nombre + "</td>" +
                "<td id='marca'>" + value.nom_marca + "</td>" +
                "<td id='existencia'>" + value.existencia + "</td>" +
                "<td id='imagen_url' class='hidden'>" + value.imagen_url + "</td>" +
                "<td id='precio'>" + value.precio + "</td>";
                var disable;
                //Mido nivel de Stock
                item = item + "</td>" + "<td>";
                if (value.existencia <= 0 || value.existencia == null) {
                    item = item + "<span class='label label-danger'>Sin stock</span>";
                    disable = 'disabled';
                }else if(value.existencia < value.punto_pedido){
                    item = item + "<span class='label label-warning'>Punto de pedido</span>";
                }else{
                    item = item + "<span class='label label-success'>En Stock</span>";
                }
                item = item + "</td>" + 
                "<td style='margin:0px;padding:0px;'>" +
                "<div class='btn-group' role='group'>"+
                "<button type='button' class='btn btn-sm btn-default select-product "+disable+"'><span style='margin-right:0px' class='fa fa-plus'></span></button>"+
                // "<button type='button' class='btn btn-sm btn-default ver-producto'><span style='margin-right:0px' class='fa fa-eye'></span></button>"+ 
                "</div>"              
                "</td>" +
            "</tr>";
            $("#productList").append(item);
        });
    });
}

function checkTierPrice(id,cant,callback){
    var price;
    var params = {};
    params.id = id;
    params.cant = cant;
    panelAjax("/admin_products/getprice/",params, function(data){
        return callback(data);
    });
    //return price;
}

$("#next-patient").click(function() {
    var val     = $('#page-patient').attr('rel');
    val         = parseInt(val) + parseInt(1);
    $('#page-patient').attr('rel',val);
    search      = $('#patientsearch').val();
    getClientes(search);
});

$("#back-patient").click(function() {
    var val     = $('#page-patient').attr('rel');
    if (val > 1) {
        val         = parseInt(val) - parseInt(1);
        $('#page-patient').attr('rel',val);
        search      = $('#patientsearch').val();
        getClientes(search);
    }
});

//al hacer click en buscar, muestra los clientes
function getClientes(search){

    $("div#spinner").fadeIn("fast");
    $("#list-cliente").hide();
    var params = {};
    params.search   = search;
    params.page     = $('#page-patient').attr('rel');
    if (params.page < 0) { params.page = 1; };
    panelAjax("/cliente/getClientes/",params, function(data){
        $("#list-cliente").html('');
        $(".result-search-patient").html(data.clientes.length + ' de ' + data.total + ' clientes');
        if (data.clientes.length == 0) {
            $('.pagination').fadeOut(500);
            var item = "<div class='col-md-12'>" +
                "<div class='panel panel-default'>" +
                    "<div class='panel-body'>" +
                        "<p style='text-align:center;'>No se encontraron clientes</p>" + 
                    "</div>" +
                "</div>" +
            "</div>";
            $("#list-cliente").append(item);
        }else{
            pager = data.page + " de " + data.pages + "</span>";

            if (data.page == 1) {
                $("#back-patient").hide();
                $("#back-patient-disabled").show();
                $("#next-patient").show();
                $("#next-patient-disabled").hide();
            }
            $(".pagination-data").html(pager);
            if (data.page < data.pages) {
                $('.pagination').fadeIn(500);
                if (data.page > 1) {
                    $("#back-patient").show();
                    $("#next-patient").show();
                    $("#back-patient-disabled").hide();
                    $("#next-patient-disabled").hide();
                };
            }else if(data.page == data.pages){
                $("#next-patient").hide();
                $("#next-patient-disabled").show();
            }

            $.each(data.clientes, function( index, value ) {

                console.log('value');
                console.log(value);
                     var item = "<div id='" + value.id + "'title='" + value.nombre + " " + value.apellido + "' rel='" + value.id + "'attr-direccion='"+ value.direccion +"'   class='select-patient col-md-4' style='cursor:pointer;'>" +
                    "<!-- CONTACT ITEM -->" + 
                    "<div class='panel panel-default'>" +
                        "<div class='profile-control-left'>" + 
                            "<div class='panel-body profile'>" + 
                                "<div class='profile-image'>" +
                                    "<img src='" + value.imagen_url + "' alt='" + value.cuit + "'" +
                                "</div>" + 
                                "<div class='profile-data'>" +
                                    "<div class='profile-data-name'>" + value.nombre + " " + value.apellido + "</div>" +
                                    "<div class='profile-data-direccion'>" + value.direccion + "</div>" + 
                                    "<div class='profile-data-cuit'>Cuit: " + value.cuit + "</div>" + 
                                    "<div class='profile-data-tipo_cliente'>" + value.tipo_cliente + "</div>" + 
                                    "<div class='profile-data-descuento hidden'>" + value.descuento + "</div>" + 
                                    "<div class='profile-data-telefono'> Tel: " + value.telefono + "</div>" + 
                                    "<div class='profile-data-email'> " + value.email + "</div>" + 
                                "</div>" +
                                "<div class='profile-controls'>";
                                    if(value.nom_estado == 'Deudor') {
                                    item = item + "<a class='profile-control-right-up' style='font-size:26px;border-color:#FF4D4D;right: 10px; top:13px;'>" +
                                        "<span class='fa fa-exclamation-circle' data-toggle='tooltip' data-original-title='El cliente posee una deuda.'></span>" + 
                                    "</a>";
                                    }
                                item = item + "</div>" +
                            "</div>" +
                        "</div>" +
                    "</div>" +
                    "<!-- END CONTACT ITEM -->" + 
                "</div>";            
                $("#list-cliente").append(item);
            });
        }
    });
    $("div#spinner").fadeOut("fast");
    $("#list-cliente").show();
}


//Calcula total con descuento e iva
var calculateTotal = function(){
    var tot_discount, enviototal, total;
    total = parseFloat($("#subtotal_cost_hidden").val()); 
    // tot_discount = parseFloat($('#rdiscount_hidden').val());

    costo_envio = parseFloat($('#shipping').val());

    if ($('#switch-descuento').val() == 'false') {
        subtotal = total;
        $("#tot_discount").html("<span style='float:left'>Descuento:</span><span style='float:right;padding-right: 22px;'>0 %</span>");
        // $("#tot_discount").hide();

    }else{
        disc = descuento * total / 100;
        subtotal = (total - disc);
        $("#tot_discount").html("<span style='float:left'>Descuento:</span><span style='float:right;padding-right: 22px;'>"+descuento+" %</span>");
        
    }

    if ($('#switch-envio').val() == 'false') {
        enviototal = 0;
        $("#envio").html("<span style='float:left'>Envio:</span><span style='float:right;padding-right: 22px;'>$0</span>");
        // $("#envio").hide();

    }else{
        enviototal = 50;
        $("#envio").html("<span style='float:left'>Envío:</span><span style='float:right;padding-right: 22px;'>$"+enviototal.toFixed(2)+"</span>");
        $("#envio").show();

    }

    iva  = 21 * subtotal / 100;
   
    if (subtotal >= 0) {
        $(".buttonNext").removeClass('buttonDisabled');
        total = subtotal + iva + enviototal;
        total = total.toFixed(2); 
    }else{
        $(".buttonNext").addClass('buttonDisabled');
        setTimeout(function() {
            $("#detalle-producto").modal();
        }, 300);
        
    
    }
    
   

    $("#tot_iva").html("<span style='float:left'>IVA:</span><span style='float:right;padding-right: 22px;'>21%</span>"); 
    
    $("#tot_donation").html("<span style='float:left'>TOTAL:</span><span style='float:right;padding-right: 22px;'>$"+total+"</span>");
    
    $('#label-total').text('$'+total);        
    $('#total_cost_hidden').val(total);
    $('#fee_shipping').val(shipping);
    $('#fee_convenience').val(convenience);

}

</script>


<!-- END SCRIPTS --> 