<div class="panel panel-default col-md-7">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Resumen</h3>
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        
                                        <div class="container">
                                            <div class="row">
                                                <div class="span4">
                                                    <img src="/img/gabinando.png" title="logo">
                                                    <address>
                                                        <strong>Gabinando S.R.L</strong><br>
                                                        Santiago 1573<br>
                                                        Rosario, Santa Fe<br>
                                                    </address>
                                                </div>
                                                <div class="span4 well">
                                                    <table class="invoice-head">
                                                        <tbody>
                                                            <tr>
                                                                <td class="pull-right"><strong>Customer #</strong></td>
                                                                <td><?php echo $invoice->customer; ?></td>
                                                            </tr>
                                                            <tr>
                                                                <td class="pull-right"><strong>Invoice #</strong></td>
                                                                <td><?php echo $invoice->id; ?></td>
                                                            </tr>
                                                            <tr>
                                                                <td class="pull-right"><strong>Date</strong></td>
                                                                <td><?php echo date('M j, Y', $invoice->date); ?></td>
                                                            </tr>
                                                            <tr>
                                                                <td class="pull-right"><strong>Period</strong></td>
                                                                <td><?php echo date('M j, Y', $invoice->period_start) .' to ' . date('M j, Y', $invoice->period_end); ?></td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="span8">
                                                    <h2>Factura</h2>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="panel-body">
                                                    <table class="table table-bordered">
                                                        <thead>
                                                            <tr>
                                                                <th>Código</th>
                                                                <th>Descripción</th>
                                                                <th>$</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>

                                                            <?php
                                                            $total = 0;
                                                            foreach($invoice->lines->subscriptions as $subscription){
                                                                echo '<tr>';
                                                                $amount = $subscription->amount / 100;
                                                                echo '<td>Agora '.$subscription->plan->name.' ($'.number_format($subscription->plan->amount / 100,2).'/'.$subscription->plan->interval.')</td>';
                                                                echo '<td>' . date('M j, Y', $subscription->period->start) .' - ' . date('M j, Y', $subscription->period->end). '</td>';
                                                                echo '<td>$' . number_format($amount,2).'</td>';
                                                                $total += $amount;
                                                                echo '</tr>';
                                                            }
                                                            if(isset($invoice->discount)){
                                                                echo '<tr>';
                                                                echo '<td>'.$invoice->discount->coupon->id.' ('.$invoice->discount->coupon->percent_off.'% off)</td>';
                                                                $discount = $total * ($invoice->discount->coupon->percent_off/100);
                                                                echo '<td>&nbsp;</td>';
                                                                echo '<td>-$'.number_format($discount,2).'</td>';
                                                                echo '</tr>';
                                                            }
                                                            ?>
                                                            <tr>
                                                                <td>&nbsp;</td>
                                                                <td><strong>Total</strong></td>
                                                                <td><strong>$<?php echo number_format(($invoice->total / 100), 2); ?></strong></td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="span6 offset1 well invoice-thank">
                                                    <h5 style="text-align:center;">Thank You!</h5>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="span3">
                                                    <strong>Teléfono:</strong> <a href="tel:555-555-5555">0341-4406614</a>
                                                </div>
                                                <div class="span3">
                                                    <strong>Email:</strong> <a href="mailto:hello@5marks.co">contacto@gabinandosrl.com.ar</a>
                                                </div>
                                                <div class="span3">
                                                    <strong>Website:</strong> <a href="http://5marks.co">http://5marks.co</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    
                                </div>
                            </div>