<?php         
$this->title = "Panel principal";
$this->headTitle($this->title);
?>

<script>
$(".xn-icon-button").fadeIn();
</script>

<!-- BREADCRUMB -->
  <ul class="breadcrumb">                 
      <li class="active">Panel principal</li>
  </ul>

<!-- PAGE CONTENT WRAPPER -->
  <div class="page-content-wrap">
  <!-- ROW 1 / WIDGETS -->
    <div class="row">
      <div class="col-md-4">   
        <div class="widget widget-default widget-carousel">
          <div class="owl-carousel" id="owl-example">
              <div>           
              <div class="widget-title">Total ventas del mes</div>
              <div class="widget-subtitle"><?php echo date('m-Y') ?></div>
              <div class="widget-int"><?php echo $this->cantVentasMes['total'] ?></div>
          </div>
          <div>                                    
              <div class="widget-title">Total ventas de hoy</div>
              <div class="widget-subtitle">Hoy</div>
              <div class="widget-int"><?php echo $this->cantVentas['total'] ?></div>
          </div>
         <!--  <div>                                    
              <div class="widget-title">Clientes sin deudas</div>
              <div class="widget-subtitle">Cancelled</div>
              <div class="widget-int"><?php echo $this->storefront_donationsCount['cancelled'] ?></div>
          </div> -->
          
          </div>                            
          <div class="widget-controls"></div>
        </div> 
      </div>
      <!-- 5 Clientes con mas ventas por mes -->
      <div class="col-md-4">   
        <div class="widget widget-default widget-carousel ">
          <div class="owl-carousel" id="owl-example">
            <?php if ($this->clientesMasVentas) { ?>
              <?php foreach ($this->clientesMasVentas as $clienteMasVenta) { ?>
                <div>                                    
                    <div class="widget-title"><?php echo ($clienteMasVenta['razon_social']) ?  $clienteMasVenta['razon_social'] :  $clienteMasVenta['nombre'].' ' .$clienteMasVenta['apellido'];  ?></div>                                                                        
                    <div class="widget-subtitle">Cantidad de compras del mes</div>
                    <div class="widget-int"><?php echo $clienteMasVenta['cant_compras'] ?></div>
                </div>
              <?php } ?>
              <?php }else{ ?>
                <div>                                    
                    <div class="widget-title">No hubo ventas en el mes</div>
                </div>
              <?php } ?>
          </div>                            
          <div class="widget-controls"></div>
        </div>  
      </div>  
      <!-- Ventas por tipo de cliente x mes -->
      <!-- <div class="col-md-4">   
        <div class="widget widget-default widget-carousel ">
          <div class="owl-carousel" id="owl-example">
              <div>                                    
                  <div class="widget-title">Ventas x mes</div>                                                                        
                  <div class="widget-subtitle"><?php echo date('m-d-Y') ?></div>
                  <div class="widget-int"><?php echo $this->donationsCount['total'] ?></div>
              </div>
              <div>                                    
                  <div class="widget-title">Talleres</div>
                  <div class="widget-subtitle">Successful</div>
                  <div class="widget-int"><?php echo $this->donationsCount['success'] ?></div>
              </div>
              <div>                                    
                  <div class="widget-title">Particulares</div>
                  <div class="widget-subtitle">Pending</div>
                  <div class="widget-int"><?php echo $this->donationsCount['pending'] ?></div>
              </div>
              <div>                                    
                  <div class="widget-title">Consumidor Final</div>
                  <div class="widget-subtitle">Cancelled</div>
                  <div class="widget-int"><?php echo $this->donationsCount['cancel'] ?></div>
              </div>
              <div>                                    
                  <div class="widget-title">Mayorista</div>
                  <div class="widget-subtitle">Future</div>
                  <div class="widget-int"><?php echo $this->futureDonationsCount ?></div>
              </div>
          </div>                            
          <div class="widget-controls"></div>
        </div>  
      </div>  -->
      <!-- Productos con stock critico -->
      <!-- <div class="col-md-3">   
        <div class="widget widget-default widget-carousel ">
          <div class="owl-carousel" id="owl-example">
              <div>                                    
                  <div class="widget-title">Productos con stock crítico</div>                                                                        
                  <div class="widget-subtitle">Total</div>
                  <div class="widget-int"><?php echo $this->donationsCount['total'] ?></div>
              </div>
              <div>                                    
                  <div class="widget-title">Talleres</div>
                  <div class="widget-subtitle">Successful</div>
                  <div class="widget-int"><?php echo $this->donationsCount['success'] ?></div>
              </div>
              <div>                                    
                  <div class="widget-title">Particulares</div>
                  <div class="widget-subtitle">Pending</div>
                  <div class="widget-int"><?php echo $this->donationsCount['pending'] ?></div>
              </div>
              <div>                                    
                  <div class="widget-title">Consumidor Final</div>
                  <div class="widget-subtitle">Cancelled</div>
                  <div class="widget-int"><?php echo $this->donationsCount['cancel'] ?></div>
              </div>
              <div>                                    
                  <div class="widget-title">MAyoristas</div>
                  <div class="widget-subtitle">Future</div>
                  <div class="widget-int"><?php echo $this->futureDonationsCount ?></div>
              </div>
          </div>                            
          <div class="widget-controls"></div>
        </div>  
      </div> -->

      <div class="col-md-4">   
          <div class="widget widget-default widget-item-icon">
            <div class="widget-item-left">
                <span class="fa fa-arrow-down"></span>
            </div>                             
            <div class="widget-data">
              <?php if($this->cantPtoPedido["cantPtoPedido"] == 0) {?>
              <div class="widget-title" style="position:relative;top:35px;">
                  No hay productos con stock crítico
              </div>
              <?php } else { ?>
              <div id="widget_cancelled" class="widget-int num-count" style="font-size:25px;">
                  <?php echo $this->cantPtoPedido["cantPtoPedido"]; ?> 
              </div>
              <div class="widget-title">
                Productos con stock crítico
              </div>
              <?php } ?>
            </div>
          </div>
      </div>


      <!-- COLUMN 1 / VENTAS HOY -->
      <div class="col-md-4">   
          <div class="widget widget-default widget-item-icon">
            <div class="widget-item-left">
                <span class="fa fa-shopping-cart"></span>
            </div>                             
            <div class="widget-data">
              <?php if(!isset($this->cantVentas)) {?>
              <div class="widget-title" style="position:relative;top:35px;">
                  No hubo ventas hoy
              </div>
              <?php } else { ?>
              <div id="widget_successful" class="widget-int num-count" style="font-size:25px;">
                  <?php echo $this->cantVentas["total"]; ?> 
              </div>
              <div class="widget-title">
                  Ventas de hoy
              </div>
              <?php } ?>
            </div>
        </div>
      </div>
    <!-- COLUMN 2 / FACTURAS POR COBRAR OK -->
      <div class="col-md-4">   
          <div class="widget widget-default widget-item-icon">
            <div class="widget-item-left">
                <span class="fa fa-info-circle"></span>
            </div>                             
            <div class="widget-data">
              <?php if(!isset($this->deudas)) {?>
              <div class="widget-title" style="position:relative;top:35px;">
                  No hay facturas por cobrar
              </div>
              <?php } else { ?>
              <div id="widget_cancelled" class="widget-int num-count" style="font-size:25px;">
                  <?php echo $this->deudas; ?> 
              </div>
              <div class="widget-title">
                Facturas por cobrar
              </div>
              <?php } ?>
            </div>
          </div>
      </div>

    <!-- COLUMN 2 / $$ FACTURAS POR COBRAR -->
      <div class="col-md-4">
         <div class="widget widget-default widget-item-icon">
            <div class="widget-item-left">
                <span class="fa fa-thumbs-o-down"></span>
            </div>                             
            <div class="widget-data">
                <?php if(!isset($this->totalDeuda)) {?>
                <div class="widget-title" style="position:relative;top:35px;">
                    Los clientes están al día
                </div>
                <?php } else { ?>
                <div id="widget_pending" class="widget-int num-count" style="font-size:25px;">
                   $<?php echo $this->totalDeuda; ?> 
                </div>
                <div class="widget-title">
                    Total de facturas sin cobrar
                </div>
                <?php } ?>
            </div>
          </div>  
      </div>
    <!-- COLUMN 3 / WAITING REQUEST WIDGET -->
      <!-- <div class="col-md-3">
         <div class="widget widget-default widget-item-icon">
              <div class="widget-item-left">
                  <span class="fa fa-clock-o"></span>
              </div>                             
              <div class="widget-data">
                  <?php if(!isset($this->widgetsData['Waiting'])) {?>
                  <div class="widget-title" style="position:relative;top:35px;">
                      No data
                  </div>
                  <?php } else { ?>
                  <div id="widget_waiting" class="widget-int num-count" style="font-size:25px;">
                      <?php echo $this->widgetsData['Waiting']; ?> 
                  </div>
                  <div class="widget-title">
                      DATOS
                  </div>
                  <?php } ?>
              </div>
          </div>  
      </div> -->
    </div>
  

<!-- MODAL ALERT -->
  <!-- <div id="modalAlert" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Error</h4>
            </div>
            <div class="modal-body">
                <p>An error as ocurred on update.</p>
                <p>Here is some info about the error.</p>
                <p id="alertText" class="text-warning"><small></small></p>
            </div>
        </div>
    </div>
  </div> -->


<!-- THIS PAGE PLUGINS -->
  <script type="text/javascript" src="/admin-public/js/plugins/scrolltotop/scrolltopcontrol.js"></script>
  <script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datepicker.js"></script>
  <script type='text/javascript' src='/admin-public/js/plugins/custom/dataTables.rowsGroup.js'></script>
  <script type='text/javascript' src='/admin-public/js/request.js'></script>
  <script type='text/javascript' src='/admin-public/js/requests_table.js'></script>
  <script type="text/javascript" src="/admin-public/js/plugins/owl/owl.carousel.min.js"></script>                 


