<?php         
$this->title = "Detalle de pedido";
$this->headTitle($this->title);
?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Panel Principal</a></li>
    <li><a href="/pedido/list">Pedido</a></li>
    <li class="active">Detalle</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-sm-12">
        <!-- EDIT FORM -->
            <form id="edit-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Detalle</strong> de pedido</h3>
                        <?php ($this->pedido["recibido"] == 0) ? $disabled = ''  : $disabled = 'disabled' ?>
                            <a class="btn btn-primary btn-pedido-recibido pull-right <?php echo $disabled; ?> ">Pedido recibido completo</a>
                            <input name="id_pedido" id="id_pedido" type="hidden" value="<?php  echo $this->pedido['id_ped']; ?> ">
                    </div>

                    <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="invoice-title">
                                       <img src="/resources/logo.png"> <h3 class="pull-right">Pedido N°: #<?php  echo $this->pedido['id_ped']; ?> </h3>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <address>
                                            <strong>GABINANDO S.R.L</strong><br>
                                                Santiago 1569<br>
                                                2000 - Rosario<br>
                                                IVA Responsable Inscripto<br>
                                                CUIT: 30-33301419-0<br>
                                                Inicio Actividades: 05/04/1966
                                            </address>
                                        </div>
                                        <div class="col-xs-6 text-right">
                                            <address>
                                            <strong>Datos del proveedor</strong><br>
                                            <?php if ($this->pedido["razon_social"])    : ?>
                                                Razón social: <?php echo $this->pedido["razon_social"]?><br>
                                            <?php endif ?>
                                            <?php if ($this->pedido["cuit"] != 0)  : ?>

                                                CUIT: <?php echo $this->pedido["cuit"]?><br>
                                                <?php echo $this->pedido["direccion"]?><br>
                                            <?php endif ?>
                                            </address>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-xs-6">
                                        </div>
                                        <div class="col-xs-6 text-right">
                                            <address>
                                                <strong>Fecha:</strong><br>
                                                <?php echo date("d/m/Y h:i:s", strtotime($this->pedido["fecha"])); ?><br><br>
                                            </address>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h3 class="panel-title"><strong>Resumen</strong></h3>
                                        </div>
                                        <div class="panel-body">
                                            <div class="table-responsive">
                                                <table class="table table-condensed">
                                                    <thead>
                                                        <tr>
                                                            <td class="text-center"><strong>Cantidad</strong></td>
                                                            <td class="text-center"><strong>Código</strong></td>
                                                            <td class="text-right"><strong>Descripción</strong></td>
                                                            <td class="text-right"><strong>Código proveedor</strong></td>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                         <?php foreach ($this->pedido["detalle"] as $detalle) { ?>
                                                        <tr>
                                                            <td class="text-center"><?php echo  $detalle['cantidad'] ?></td>
                                                            <td class="text-center"><?php echo  $detalle['codigo'] ?></td>
                                                            <td class="text-right"><?php echo  $detalle['descripcion'] ?></td>
                                                            <td class="text-right"><?php echo $detalle['codigo_producto_proveedor']?></td>
                                                        </tr>
                                                    <?php } ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        

                        

                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-default" type="button" onclick="history.back()">Volver</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                
<!-- <div class="modal fade" id="modal_pedido_recibido" tabindex="-1" role="dialog" aria-labelledby="smallModalHead" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Productos Equivalentes</h4>
                </div>
                <div class="modal-body " id="equivalen">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <!-- <a type="button" class="btn btn-primary" id="btnYes">Si</a> -->
                </div>
            </div>
        </div>
    </div>
</div> -->

<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datepicker.js"></script> 
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-select.js"></script>   
<script type=“text/javascript” src=“/js/plugins/jquery-validation/jquery.validate.js”></script>              

<!-- END THIS PAGE PLUGINS -->

<script>
    $().ready(function() {
        
    });
        $(".btn-pedido-recibido").click(function(event){
            $("#modal_pedido_recibido").html();
            var params = {};
            params.id_pedido = $('#id_pedido').val();

            panelAjax("/pedido/recibido",params, function(data){
                if (data) {
                    location.reload();
                }
                
            })

        });
   



</script>