<?php         
$this->title = "Detalle de pedido";
$this->headTitle($this->title);
?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Panel Principal</a></li>
    <li><a href="/pedido/detalle">Pedido</a></li>
    <li class="active">Detalle</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-sm-12">
        <!-- EDIT FORM -->
            <form id="edit-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Detalle</strong> de pedido</h3>
                    </div>
                    <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="invoice-title">
                                       <img src="/resources/logo.png"> <h3 class="pull-right">Pedido N°: #<?php echo $this->pedido['id']; ?> </h3>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <address>
                                            <strong>GABINANDO S.R.L</strong><br>
                                                Santiago 1569<br>
                                                2000 - Rosario<br>
                                                IVA Responsable Inscripto<br>
                                                CUIT: 30-33301419-0<br>
                                                Inicio Actividades: 05/04/1966
                                            </address>
                                        </div>
                                        <div class="col-xs-6 text-right">
                                            <address>
                                            <strong>Datos del proveedor</strong><br>
                                            <?php if ($this->pedido["razon_social"])    : ?>
                                                Razón social: <?php echo $this->pedido["razon_social"]?><br>
                                            <?php endif ?>
                                            <?php if ($this->pedido["cuit"] != 0)  : ?>

                                                CUIT: <?php echo $this->pedido["cuit"]?><br>
                                                <?php echo $this->pedido["direccion"]?><br>
                                            <?php endif ?>
                                            </address>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-xs-6">
                                        </div>
                                        <div class="col-xs-6 text-right">
                                            <address>
                                                <strong>Fecha:</strong><br>
                                                <?php echo date("d/m/Y h:i:s", strtotime($this->pedido["fecha"])); ?><br><br>
                                            </address>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h3 class="panel-title"><strong>Resumen</strong></h3>
                                        </div>
                                        <div class="panel-body">
                                            <div class="table-responsive">
                                                <table class="table table-condensed">
                                                    <thead>
                                                        <tr>
                                                            <td class="text-center"><strong>Cantidad</strong></td>
                                                            <td class="text-center"><strong>Código</strong></td>
                                                            <td class="text-center"><strong>Descripción</strong></td>
                                                            <td class="text-right"><strong>Código proveedor</strong></td>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                         <?php foreach ($this->pedido["detalle"] as $detalle) { ?>
                                                        <tr>
                                                            <td class="text-center"><?php echo  $detalle['cantidad'] ?></td>
                                                            <td class="text-center"><?php echo  $detalle['codigo'] ?></td>
                                                            <td class="center"><?php echo  $detalle['descripcion'] ?></td>
                                                            <td class="text-center"><?php echo $detalle['codigo_producto_proveedor']?></td>
                                                        </tr>
                                                    <?php } ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        

                        

                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-default" type="button" onclick="history.back()">Volver</button>
                        <button class="btn btn-primary pull-right">Guardar</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datepicker.js"></script> 
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-select.js"></script>   
<script type=“text/javascript” src=“/js/plugins/jquery-validation/jquery.validate.js”></script>              

<!-- END THIS PAGE PLUGINS -->

<script>

var regexp = /^\d+(\,\d{1,2})?$/;
var validator;
$().ready(function() {
    validator = $("#add-form").validate({
        ignore: '',
        rules: {
            razon_social: {
                required: true
            },
            apellido: {
                required: true
            },
            direccion: {
                required: true,
            },
            telefono: {
                required: true,
            },
            cuit: {
                required: true,
                validarcuit: true
            },
            email: "required"
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        messages: {
            razon_social: {
                required: "Campo requerido",
            },
            direccion: {
                required: "Campo requerido"
            },
            telefono: {
                required: "Campo requerido"
            },
            cuit: {
                required: "Campo requerido"
            },
            email: {
                required: "Campo requerido"
            }

        }
    });
});
$.validator.addMethod("validarprecio", function (value, element) {
    var regex = new RegExp(regexp);
    return regex.test(value);
});
$.validator.addMethod('validarcuit', function (value, element) {
        return this.optional(element) || /^\d{11}$/.test(value);
}, "El formato debe ser (00-00000000-0). No ingrese los guiones");
</script>