<?php         
$this->title = "Lista depedidos";
$this->headTitle($this->title);
?>

<script>
$(".xn-icon-button").fadeIn();
</script>

<!-- BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="/">Panel Principal</a></li>
        <li><a href="#">Pedidos</a></li>
        <li class="active">Listado</li>
    </ul>

<!-- PAGE CONTENT WRAPPER -->
    <div class="row">    
        <div class="col-sm-12">
            <div class="page-content-wrap">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title-box">
                            <h3>Lista de pedidos</h3>
                        </div>  
                        <button class="btn btn-primary pull-right" onclick="agregarPedido()" data-toggle="dropdown"><span class="fa fa-plus" ></span> Nuevo</button>
                    </div>
                        
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table datatable table-striped" id="lista_vta">
                                <thead>
                                    <tr>
                                        <th width="50">ID</th>
                                        <th>Proveedor</th>
                                        <th>Cuit</th>
                                        <th>Dirección</th>
                                        <th>Teléfono</th>
                                        <th>Email</th>
                                        <th>Fecha</th>
                                        <th width="150" class="no-sortable text-center">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->listadoPedidos as $pedido): ?>
                                    <tr id="<?php echo $pedido['id'] ?>" class="element-id">
                                        <td class="text-center"><?php echo $pedido['id_ped'] ?></td>
                                        <td><?= ($pedido['razon_social'] != NULL) ? $pedido['razon_social'] :  $pedido['nombre'].' '. $pedido['apellido']?></td>
                                        <td><?php echo $pedido['cuit'] ?></td>
                                        <td><?php echo $pedido['direccion'] ?></td>
                                        <td><?php echo $pedido['telefono'] ?></td>
                                        <td><?php echo $pedido['email'] ?></td>
                                        <td><?php echo $pedido['fecha'] ?></td>
                                        <td class="text-center">
                                            <button class="btn btn-default btn-rounded btn-condensed btn-sm" onclick="detallePedido(<?php echo $pedido['id_ped'] ?>)"><span class="fa fa-eye"></span></button>
                                            <button class="btn btn-danger btn-rounded btn-condensed btn-sm btn-delete" id="<?php echo $pedido['id'] ?>"><a href="#" data-toggle="tooltip" title="Cancelar pedido"><span class="fa fa-remove" data-toggle="modal" data-target="#delete_modal"></span></a></button>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- MODAL ALERT -->
    <div class="modal animated fadeIn" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="smallModalHead" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Confirmación</h4>
                </div>
                <div class="modal-body">
                    <p>Desea anular el pedido?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-primary" id="btnYes">Si</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function(){
            
            var id = 0;

            $(".btn-delete").click(function(event){
                id = $(this).attr('id');
            });

            $("#btnYes").click(function(){
                window.location.href = "/pedido/remove/id/" + id;
            })

        });
    var detallePedido = function(id){
        window.location.href = "/pedido/detalle/id/" + id;
    }
    var agregarPedido = function(){
        window.location.href = "/pedido/add";
    }
    </script>

 