<html>
	<head>
		<title>KFC</title>
	</head>
	<body>
		<p style='text-align:center;width:100%;'>
			<img src='<?php echo $this->baseUrl(); ?>/resources/logo.png' style="background:#ffd672" width="200px">
		</p>
		<table style='text-align:center;width:100%;margin-top:50px;margin-bottom:50px;'>
			<tbody>
				<tr>
					<td style="text-align:center;color:#000;padding-top:25px;line-height:130%;font-size:14px;">
						<?= $this->message ?>
					</td> 
				</tr>
				<tr>
					<td style="color:#000;padding-top:25px;padding-bottom:25px;padding-left:30px;padding-right:30px;text-align:center;font-size:10px;">
						<em>
							Este mail es de caracter informativo para saber el día y el monto de la compra realizada <br>
							
						</em>
						<!-- <div style="color:#fed75f;margin-top:30px;font-size:12px;">
							<a href="<?= front_uri ?>/index/politicas" style="color:red;text-decoration:underline" target="_blank">Privacidad</a> |
							<a href="<?= front_uri ?>/index/terminos" style="color:red;text-decoration:underline" target="_blank">Términos de uso</a>
						</div> -->
					</td>
				</tr>
			</tbody>
		</table>
		<p style='text-align:center;width:100%;'>
			<span style='text-align:center;width:100%;'>
				<img border="0" src="<?= front_uri ?>/resources/footer-mail.png" class="CToWUd">
			</span>
		</p>
	</body>
</html>