<html>
	<head>
		<title>Gabinando</title>
	</head>
	<body>
		<p style='text-align:center;width:100%;'>
			<img src='/resources/logo.png' style="background:#ffd672" width="200px">
		</p>
		<table style='text-align:center;width:100%;margin-top:50px;margin-bottom:50px;'>
			<tbody>
				<tr>
					<td style="text-align:center;color:#000;padding-top:25px;line-height:130%;font-size:14px;">
						<?= $this->message ?>
					</td> 
				</tr>
				<tr>
					<td style="color:#000;padding-top:25px;padding-bottom:25px;padding-left:30px;padding-right:30px;text-align:center;font-size:10px;">
						<em>
							Este mail es de caracter informativo para informar el día, monto y forma de pago de la compra realizada en Gabinando S.R.L<br>
							
						</em>
					</td>
				</tr>
			</tbody>
		</table>
	</body>
</html>