<?php         
$this->title = "Order's Footer";
$this->headTitle($this->title);
?>       
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="#">Dashboard</a></li>
    <li><a href="#">Modules</a></li>                  
    <li><a href="/settings">Settings</a></li>
</ul>
<!-- END BREADCRUMB -->              

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <div class="row">
        <div class="col-md-12">
            
            <form id="edit-form" class="form-horizontal" method="post" >
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Edit</strong> order's footer</h3>
                    <ul class="panel-controls">
                    </ul>
                </div>

                <div class="panel-body">                                                                        
                    <div class="form-group">
                        <label class="col-md-3 col-xs-12 control-label">Order's footer code</label>
                        <div class="col-md-6 col-xs-12">                                            
                            <div class="input-group">
                                <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                <textarea rows="10" name="value" id="value" class="form-control"><?php echo $this->data['value'] ?></textarea>
                            </div>                                            
                        </div>
                    </div>

                </div>
                <div class="panel-footer">
                    <button class="btn btn-default" type="button" onclick="history.back()">Back</button>
                    <button class="btn btn-primary pull-right">Save</button>
                </div>
            </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin-public/js/additional-methods.min.js"></script>
<!-- END THIS PAGE PLUGINS -->

<script>
$().ready(function() {

    $("#edit-form").validate({
        rules: {
            value: "required",
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        }
    });
});
</script>