<?php         
$this->title = "Editar marca";
$this->headTitle($this->title);
?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Panel Principal</a></li>
    <li><a href="/marca/list">Marcas</a></li>
    <li class="active">Editar</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <div class="row">
        <div class="col-sm-12">
        <!-- EDIT FORM -->
            <form id="edit-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Editar</strong> Marca</h3>
                    </div>

                    <div class="panel-body">
                    
                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Nombre</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="nombre" type="text" class="form-control" value="<?php echo $this->data['nombre'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                       <!--  <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Descripción</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="description" type="text" class="form-control" value="<?php echo $this->data['description'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="text-center" id="user_image">
                            <img src="<?php echo $this->data['image_url'] ?>" class="img-thumbnail" width="200px">
                            <span class="help-block">Imagen actual</span>
                        </div>

                        <div class="form-group" id="form-group-cinema" >
                            <label class="col-sm-3 col-xs-12 control-label">Cinema</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-suitcase"></span></span>
                                    <select name="id_cinema" id="id_cinema" type="text" class="form-control select">
                                        <option value="">Selecciona Rubro</option>
                                        <?php
                                           foreach ($this->cinemasList as $key => $cinema) {
                                                echo "<option value={$cinema['id_cinema']}>{$cinema['name']}</option>";
                                            }
                                        ?>
                                    </select>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Imagen</label>
                            <div class="col-sm-6 col-xs-12">               
                                <input name="avatar_url" type="file" class="fileinput btn-primary" title="Browse file"/>
                            </div>
                        </div> -->

                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-default" type="button" onclick="history.back()">Volver</button>
                        <button class="btn btn-primary pull-right">Guardar</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<!-- END THIS PAGE PLUGINS -->

<script>
$().ready(function() {

    $("#edit-form").validate({
        rules: {
            nombre: "required",
            // description: "required",
           
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        }
    });
});
</script>