<?php         
$this->title = "Agregar nuevo cliente";
$this->headTitle($this->title);
?>
<!-- BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Panel Principal</a></li>
    <li><a href="/user/list">Cleinte</a></li>
    <li class="active">Nuevo</li>
</ul>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-sm-12">
            <!-- ADD FORM -->
            <form id="add-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Nuevo</strong> Cliente</h3>
                        <ul class="panel-controls">
                        </ul>
                    </div>

                    <div class="panel-body">

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Nombre</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="nombre" id="nombre" type="text" class="form-control"/>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Apellido</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="apellido" id="apellido" type="text" class="form-control"/>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Cuit</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="cuit" id="cuit" type="text" class="form-control"/>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Email</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="email" id="email" type="text" class="form-control"/>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Teléfono</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="telefono" id="telefono" type="text" class="form-control"/>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Dirección</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="direccion" id="direccion" type="text" class="form-control"/>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group" id="form-group-estado" >
                            <label class="col-sm-3 col-xs-12 control-label">Estado</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-suitcase"></span></span>
                                    <select name="estado" id="estado" type="text" class="form-control select">
                                        <option value="">Selecciona Estado</option>
                                        <?php 
                                        foreach ($this->listadoEstados as $key => $estado): ?>
                                        <option <?php echo $this->data['id'] == $estado['id'] ? "selected" : '' ; ?> value=<?php echo  $estado['id'] ?>><?php echo $estado['nombre']?></option>

                                        <?php endforeach; ?>
                                    </select>
                                </div> 
                            </div>
                        </div> 

                        <div class="form-group" id="form-group-estado" >
                            <label class="col-sm-3 col-xs-12 control-label">Tipo de cliente</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-suitcase"></span></span>
                                    <select name="id_tipo_cliente" id="id_tipo_cliente" type="text" class="form-control select">
                                        <option value="">Selecciona Tipo</option>
                                        <?php 
                                        foreach ($this->listadoTiposClientes as $key => $tipo): ?>
                                        <option <?php echo $this->data['id'] == $tipo['id'] ? "selected" : '' ; ?> value=<?php echo  $tipo['id'] ?>><?php echo $tipo['nombre']?></option>
                                        
                                        <?php endforeach; ?>
                                    </select>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Imagen</label>
                            <div class="col-sm-6 col-xs-12">               
                                <input name="imagen_url" id="imagen_url" type="file" class="fileinput btn-primary" accept="image/*" />
                            </div>
                        </div>

                </div>
                <div class="panel-footer">
                    <button class="btn btn-default" type="button" onclick="history.back()">Volver</button>
                    <button class="btn btn-primary pull-right">Guardar</button>
                </div>
            </div>
        </form>

    </div>
</div>                    

</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datepicker.js"></script> 
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-select.js"></script>   
<script type=“text/javascript” src=“/js/plugins/jquery-validation/jquery.validate.js”></script>

<!-- END THIS PAGE PLUGINS -->

<script>
   $('.datepicker').datepicker({
    format: 'dd-mm-yyyy',
    // startDate: '-3d'
    language: 'es'
});

   var regexp = /^\d+(\,\d{1,2})?$/;
   var validator;
   $().ready(function() {
    validator = $("#add-form").validate({
        ignore: '',
        rules: {
            id_producto: {
                required: true
            },
            id_estado: "required",
            precio: {
                required: true,
                validarprecio: true
            },
            fecha: "required"
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        messages: {
            precio: {
                required: "Campo requerido",
                validarprecio: "Deben ser numeros del tipo 30 o 30,55."
            },
            id_estado: "required",
            fecha: {
                required: "Campo requerido"
            },
            id_producto: {
                required: "Campo requerido"
            }

        }
    });
});
   $.validator.addMethod("validarprecio", function (value, element) {
    var regex = new RegExp(regexp);
    return regex.test(value);
});
</script>