<?php         
$this->title = "Editar cliente";
$this->headTitle($this->title);
?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Panel Principal</a></li>
    <li><a href="/cliente/list">Clientes</a></li>
    <li class="active">Editar</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <div class="row">
        <div class="col-sm-12">
        <!-- EDIT FORM -->
            <form id="edit-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Editar</strong> Cliente</h3>
                    </div>

                    <div class="panel-body">
                    
                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Nombre</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="nombre" type="text" class="form-control" value="<?php echo $this->data['nombre'] ?>" />
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Apellido</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="apellido" type="text" class="form-control" value="<?php echo $this->data['apellido'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Cuit</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="cuit" type="text" class="form-control" value="<?php echo $this->data['cuit'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Dirección</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="direccion" type="text" class="form-control" value="<?php echo $this->data['direccion'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Teléfono</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="telefono" type="text" class="form-control" value="<?php echo $this->data['telefono'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Email</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="email" type="email" class="form-control" value="<?php echo $this->data['email'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group" id="form-group-marca" >
                            <label class="col-sm-3 col-xs-12 control-label">Estado</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-suitcase"></span></span>
                                    <select name="estado" id="estado" type="text" class="form-control select">
                                        <option value="">Selecciona Estado</option>
                                        <?php 
                                           foreach ($this->listadoEstados as $key => $estado): ?>
                                                <option <?php echo $this->data['estado'] == $estado['id'] ? "selected" : '' ; ?> value=<?php echo  $estado['id'] ?>><?php echo $estado['nombre']?></option>
                                            
                                        <?php endforeach; ?>
                                    </select>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group" id="form-group-marca" >
                            <label class="col-sm-3 col-xs-12 control-label">Tipo de cliente</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-suitcase"></span></span>
                                    <select name="id_tipo_cliente" id="id_tipo_cliente" type="text" class="form-control select">
                                        <option value="">Selecciona Tipo</option>
                                        <?php 
                                           foreach ($this->listadoTiposClientes as $key => $tipo): ?>
                                                <option <?php echo $this->data['id_tipo_cliente'] == $tipo['id'] ? "selected" : '' ; ?> value=<?php echo  $tipo['id'] ?>><?php echo $tipo['nombre']?></option>
                                            
                                        <?php endforeach; ?>
                                    </select>
                                </div> 
                            </div>
                        </div>

                         <div class="text-center" id="user_image">
                            <img src="<?php echo $this->data['imagen_url'] ?>" class="img-thumbnail" width="200px">
                            <span class="help-block">Imagen actual</span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Imagen</label>
                            <div class="col-sm-6 col-xs-12">               
                                <input name="imagen_url" type="file" class="fileinput btn-primary" title="Browse file"/>
                            </div>
                        </div>

                        

                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-default" type="button" onclick="history.back()">Volver</button>
                        <button class="btn btn-primary pull-right">Guardar</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datepicker.js"></script> 
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-select.js"></script>   
<script type=“text/javascript” src=“/js/plugins/jquery-validation/jquery.validate.js”></script>              

<!-- END THIS PAGE PLUGINS -->

<script>

var regexp = /^\d+(\,\d{1,2})?$/;
var validator;
$().ready(function() {
    validator = $("#add-form").validate({
        ignore: '',
        rules: {
            nombre: {
                required: true
            },
            apellido: {
                required: true
            },
            direccion: {
                required: true,
            },
            cuit: {
                required: true,
                validarcuit: true
            },
            telefono: {
                required: true,
            },
            email: "required"
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        messages: {
            nombre: {
                required: "Campo requerido",
            },
            apellido: {
                required: "Campo requerido"
            },
             direccion: {
                required: "Campo requerido"
            },
            telefono: {
                required: "Campo requerido"
            },
            email: {
                required: "Campo requerido"
            }

        }
    });
});
$.validator.addMethod("validarprecio", function (value, element) {
    var regex = new RegExp(regexp);
    return regex.test(value);
});
$.validator.addMethod('validarcuit', function (value, element) {
        return this.optional(element) || /^\d{11}$/.test(value);
}, "El formato debe ser (00-00000000-0). No ingrese los guiones");
</script>