<?php         
$this->title = "Lista de clientes";
$this->headTitle($this->title);
?>

<script>
$(".xn-icon-button").fadeIn();
</script>

<!-- BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="/">Panel Principal</a></li>
        <li><a href="#">Clientes</a></li>
        <li class="active">Listado</li>
    </ul>

<!-- PAGE CONTENT WRAPPER -->
    <div class="row">    
        <div class="col-sm-12">
            <div class="page-content-wrap">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title-box">
                            <h3>Lista de clientes</h3>
                        </div>  
                        <button class="btn btn-primary pull-right" onclick="agregarCliente()" data-toggle="dropdown"><span class="fa fa-plus" ></span> Nuevo</button>
                    </div>
                        
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table datatable table-striped">
                                <thead>
                                    <tr>
                                        <th width="50">ID</th>
                                        <th>Nombre</th>
                                        <th>Apellido</th>
                                        <th>Tipo</th>
                                        <th>Cuit</th>
                                        <th>Estado</th>
                                        <th>Dirección</th>
                                        <th>Teléfono</th>
                                        <th>Email</th>
                                        <th width="150" class="no-sortable text-center">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->listadoclientes as $cliente): ?>
                                    <tr id="<?php echo $cliente['id'] ?>" class="element-id">
                                        <td class="text-center"><?php echo $cliente['id'] ?></td>
                                        <td><?php echo $cliente['nombre'] ?></td>
                                        <td><?php echo $cliente['apellido'] ?></td>
                                        <td><?php echo $cliente['nom_tipo'] ?></td>
                                        <td><?php echo $cliente['cuit'] ?></td>
                                        <td><?php echo $cliente['nom_estado'] ?></td>
                                        <td><?php echo $cliente['direccion'] ?></td>
                                        <td><?php echo $cliente['telefono'] ?></td>
                                        <td><?php echo $cliente['email'] ?></td>
                                        <td class="text-center">
                                            <button class="btn btn-default btn-rounded btn-condensed btn-sm" onclick="ctacteCliente(<?php echo $cliente['id'] ?>)"><attr data-toggle="tooltip" title="Ver estado de la cuenta corriente"><span class="fa fa-usd"></span></attr></button>
                                            <button data-id="<?php echo $cliente['id'] ?>" class="btn btn-primary btn-rounded btn-condensed btn-sm btn-ultimas-compras"><attr data-toggle="tooltip" title="Ver últimas compras"><span class="fa fa-eye"></span></attr></button>

                                           <!--  <button class="btn btn-default btn-rounded btn-condensed btn-sm btn-ultimas-compras" onclick="ultimascomprasCliente(<?php echo $cliente['id'] ?>)"><attr data-toggle="tooltip" title="Ver últimas compras"><span class="fa fa-eye"></span></attr></button> -->
                                            <button class="btn btn-default btn-rounded btn-condensed btn-sm" onclick="editarCliente(<?php echo $cliente['id'] ?>)"><span class="fa fa-pencil"></span></button>
                                            <button class="btn btn-danger btn-rounded btn-condensed btn-sm btn-delete" id="<?php echo $cliente['id'] ?>"><span class="fa fa-trash-o" data-toggle="modal" data-target="#delete_modal"></span></button>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- MODAL ALERT -->
    <div class="modal animated fadeIn" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="smallModalHead" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Confirmación</h4>
                </div>
                <div class="modal-body">
                    <p>Desea eliminar el cliente?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-primary" id="btnYes">Si</button>
                </div>
            </div>
        </div>
    </div>

    <!-- <div class="modal animated fadeIn" id="modal_ultimas_compras" tabindex="-1" role="dialog" aria-labelledby="smallModalHead" aria-hidden="true"></div> -->


<div class="modal fade" id="modal_view_orders" tabindex="-1" role="dialog" aria-labelledby="smallModalHead" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Últimas 10 compras</h4>
                </div>
                <div class="modal-body " id="orders">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <!-- <a type="button" class="btn btn-primary" id="btnYes">Si</a> -->
                </div>
            </div>
        </div>
    </div>
</div>



<script type="text/javascript" src="/admin-public/js/plugins/datatables/datatables.min.js"></script>          
<script type="text/javascript" src="/admin-public/js/plugins/datatables/dataTables.bootstrap.min.js"></script>

    <script>
        $(document).ready(function(){
            
            var id = 0;

            $(".btn-delete").click(function(event){
                id = $(this).attr('id');
            });

            $("#btnYes").click(function(){
                window.location.href = "/cliente/remove/id/" + id;
            })


            $(".btn-ultimas-compras").click(function(event){
                $("#modal_view_orders").html();
                var params = {};
                params.id_client = $(this).attr('data-id');
                panelAjax("/cliente/ultimascompras/",params, function(data){
                    console.log(data);
                    $("#orders").html('');
                    $("#orders").html(data);           
                    $('#modal_view_orders').modal('show');
                })

                // $('#btnView').attr('href', 'venta/detalle/id/'+id);
               
            });

        });
        var editarCliente = function(id){
            window.location.href = "/cliente/edit/id/" + id;
        }
       
        var ctacteCliente = function(id){
            window.location.href = "/cliente/resumen/id/" + id;
        }
        var agregarCliente = function(){
            window.location.href = "/cliente/add/";
        }
    </script>
