<div class="table-responsive">
    <table class="table table-bordered table-striped table-actions datatable-sr">
        <thead>
            <tr>
                <th># ID</th>
                <th>Fecha</th>
                <th>Forma de Pago</th>
                <th>Monto</th>
                <th>Estado</th>
                <th>Ver</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->ultimasCompras as $compra): ?>
            <tr>
                <td><?php echo $compra['id'] ?></td>
                <td><?php echo $compra['fecha'] ?></td>
                <td><?php echo $compra['forma_pago'] ?></td>
                <td><?php echo $compra['total'] ?></td>
                <td><?php $estado = ($compra['pagado'] == 1) ? 'Pagado' : 'Debe' ; echo $estado ?></td>
                <td><a target="_blank" href="/venta/detalle/id/<?php echo  $compra['id'] ?>"  id="btnView" data-id="<?php echo  $compra['id'] ?>" class="btn btn-primary btn-rounded btn-condensed btn-sm btn-view-orders"><span class="fa fa-eye"></span></a></td> 
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>