<?php 
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Gabinando');
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
	<head>
	    <?php echo $this->headMeta(); ?> 
	    <?php echo $this->headTitle(); ?>
        <!-- agrega favicon -->
        <link rel="shortcut icon" href="/admin-public/img/logo.png" type="image/x-icon">
        <!-- END agrega favicon -->
        <link href="/admin-public/css/bootstrap-switch.min.css" rel="stylesheet">

        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/admin-public/css/custom.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/admin-public/css/theme-dark.css'); ?>
        
    <!-- SCRIPTS -->
        <!-- PLUGINS -->
            <script type="text/javascript" src="/admin-public/js/plugins/jquery/jquery.min.js"></script>
            <script type="text/javascript" src="/admin-public/js/plugins/jquery/jquery-ui.min.js"></script>
            <script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap.min.js"></script>
            <script type="text/javascript" src="/admin-public/js/plugins/tour/intro.min.js"></script>
           

        <!-- TEMPLATE -->
            <script type="text/javascript" src="/admin-public/js/actions.js"></script>
            <script type="text/javascript" src="/admin-public/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
            <script type="text/javascript" src="/admin-public/js/custom.js"></script>
            <script type="text/javascript" src="/admin-public/js/plugins.js"></script>        
            <script type="text/javascript" src="/admin-public/js/plugins/icheck/icheck.min.js"></script>
            <script type='text/javascript' src='/admin-public/js/plugins/noty/jquery.noty.js'></script>
            <script type="text/javascript" src="/admin-public/js/plugins/datatables/jquery.dataTables.min.js"></script>
    </head>
    <body class="page-container-boxed">
    <!-- PAGE CONTAINER -->
        <div class="page-container <?php echo $this->minimized ? 'page-navigation-toggled page-container-wide' : ''  ?>">
        <!-- PAGE SIDEBAR -->
            <div class="page-sidebar">
                <ul class="x-navigation <?php echo $this->minimized ? 'x-navigation-minimized' : ''  ?>">
                <!-- PROFILE SECTION -->
                    <li class="xn-logo">
                        <a href="/">Gabinando</a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>
                    <li class="xn-profile">
                        <a href="#" class="profile-mini">
                            <img src="<?php  echo isset($this->user['avatar_url']) ? back_uri.$this->user['avatar_url'] : back_uri.'admin-public/img/user.png' ?>" alt="<?php echo $this->user['first_name'] ?> <?php echo $this->user['last_name'] ?>"/>
                        </a>
                        <div class="profile">
                            <div class="profile-imagen">
                                <img src="<?php  echo isset($this->user['avatar_url']) ? back_uri.$this->user['avatar_url'] : back_uri.'admin-public/img/user.png' ?>" alt="<?php echo $this->user['first_name'] ?> <?php echo $this->user['last_name'] ?>"/>
                            </div>
                            <div class="profile-data">
                                <div class="profile-data-name">
                                    <?php  echo $this->user['first_name'] ?> <?php echo $this->user['last_name'] ?>
                                </div>
                            </div>
                            
                        </div>                                                                        
                    </li>
                <!-- MENU SECTION -->
                    <li class="xn-title">Menú</li>
                    <!-- MAIN PANEL -->
                        <li <?php if($controller == 'Index') echo 'class="active"' ?> >
                            <a href="/"> <div data-step="3" data-intro="Acá podrás ver datos sobre ventas, deudas y clientes" data-position="right"><span class="fa fa-desktop"></span> <span class="xn-text">Panel Principal</span></div></a>
                        </li>     
                    <!-- ADMINISTRATORS -->    
                        
                    <!-- SETTINGS -->    
                    <?php if($this->user['admin']) ?>
                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="4" data-intro="Acá podrás gestionar los productos" data-position="right"><span class="fa fa-car" aria-hidden="true"></span><span class="xn-text">Productos</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'producto' && $action == 'add') echo 'class="active"' ?>><a href="/producto/add"><span class="fa fa-group"></span> Agregar producto</a></li>
                                <li <?php if($controller == 'producto' && $action == 'list') echo 'class="active"' ?>><a href="/producto/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                                <li <?php if($controller == 'producto' && $action == 'addoriginal') echo 'class="active"' ?>><a href="/producto/addoriginal"><span class="fa fa-group"></span> Agregar producto original</a></li>
                                 <li <?php if($controller == 'producto' && $action == 'listoriginal') echo 'class="active"' ?>><a href="/producto/listoriginal"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado originales</a></li>
                            </ul>
                        </li>
                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="5" data-intro="Acá podrás gestionar las marcas" data-position="right"><span class="fa fa-cog" aria-hidden="true"></span><span class="xn-text">Marcas</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'marca' && $action == 'add') echo 'class="active"' ?>><a href="/marca/add"><span class="fa fa-group"></span> Agregar marca</a></li>
                                <li <?php if($controller == 'marca' && $action == 'list') echo 'class="active"' ?>><a href="/marca/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                            </ul>
                        </li>
                      
                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="6" data-intro="Acá podrás gestionar los precios" data-position="right"><span class="fa fa-money" aria-hidden="true"></span><span class="xn-text">Precios</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'precio' && $action == 'add') echo 'class="active"' ?>><a href="/precio/add"><span class="fa fa-group"></span> Agregar precio</a></li>
                                <li <?php if($controller == 'precio' && $action == 'list') echo 'class="active"' ?>><a href="/precio/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                            </ul>
                        </li>
                        <?php if ($this->admin){ ?>
                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="7" data-intro="Acá podrás gestionar los proveedores" data-position="right"><span class="fa fa-users" aria-hidden="true"></span><span class="xn-text">Proveedores</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'proveedor' && $action == 'add') echo 'class="active"' ?>><a href="/proveedor/add"><span class="fa fa-group"></span> Agregar proveedor</a></li>
                                <li <?php if($controller == 'productoproveedor' && $action == 'list') echo 'class="active"' ?>><a href="/productoproveedor/list"><span class="fa fa-group"></span>Productos proveedor</a></li>
                                <li <?php if($controller == 'productoproveedor' && $action == 'costo') echo 'class="active"' ?>><a href="/productoproveedor/costo"><span class="fa fa-group"></span>Precio proveedor</a></li>
                                <li <?php if($controller == 'productoproveedor' && $action == 'list') echo 'class="active"' ?>><a href="/proveedor/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                            </ul>
                        </li>
                        <?php } ?>

                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="8" data-intro="Acá podrás gestionar los clientes" data-position="right"><span class="fa fa-user" aria-hidden="true"></span><span class="xn-text">Clientes</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'cliente' && $action == 'add') echo 'class="active"' ?>><a href="/cliente/add"><span class="fa fa-group"></span> Agregar cliente</a></li>
                                <li <?php if($controller == 'cliente' && $action == 'list') echo 'class="active"' ?>><a href="/cliente/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                            </ul>
                        </li>
                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="9" data-intro="Acá podrás gestionar los estados" data-position="right"><span class="fa fa-user" aria-hidden="true"></span><span class="xn-text">Estados</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'estado' && $action == 'add') echo 'class="active"' ?>><a href="/estado/add"><span class="fa fa-group"></span> Agregar estado</a></li>
                                <li <?php if($controller == 'estado' && $action == 'list') echo 'class="active"' ?>><a href="/estado/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                            </ul>
                        </li>
                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="10" data-intro="Acá podrás gestionar los usuarios" data-position="right"><span class="fa fa-user" aria-hidden="true"></span><span class="xn-text">Usuarios</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'usuario' && $action == 'add') echo 'class="active"' ?>><a href="/usuario/add"><span class="fa fa-group"></span> Agregar usuario</a></li>
                                <li <?php if($controller == 'usuario' && $action == 'list') echo 'class="active"' ?>><a href="/usuario/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                            </ul>
                        </li>
                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="11" data-intro="Acá podrás gestionar los tipos de cliente" data-position="right"><span class="fa fa-user" aria-hidden="true"></span><span class="xn-text">Tipos de Clientes</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'cliente' && $action == 'add') echo 'class="active"' ?>><a href="/tipocliente/add"><span class="fa fa-group"></span> Agregar tipo de cliente</a></li>
                                <li <?php if($controller == 'cliente' && $action == 'list') echo 'class="active"' ?>><a href="/tipocliente/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                            </ul>
                        </li>

                        <?php if ($this->admin["administrador"] == 1){ ?>
                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="12" data-intro="Acá podrás generar o ver los pedidos" data-position="right"><span class="fa fa-archive" aria-hidden="true"></span><span class="xn-text">Pedidos</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'pedido' && $action == 'add') echo 'class="active"' ?>><a href="/pedido/add"><span class="fa fa-group"></span> Nuevo pedido</a></li>
                                <li <?php if($controller == 'pedido' && $action == 'list') echo 'class="active"' ?>><a href="/pedido/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                            </ul>
                        </li>
                        <?php } ?>
                        
                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="13" data-intro="Acá podrás gestionar o ver las ventas" data-position="right"><span class="fa fa-archive" aria-hidden="true"></span><span class="xn-text">Ventas</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'venta' && $action == 'add') echo 'class="active"' ?>><a href="/venta/add"><span class="fa fa-group"></span> Nueva venta</a></li>
                                <li <?php if($controller == 'venta' && $action == 'list') echo 'class="active"' ?>><a href="/venta/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                            </ul>
                        </li>
                        <li id="modules-settings" class="xn-openable">
                            <a href="javascript:void(0);">
                                <div data-step="14" data-intro="Acá podrás gestionar los tipos de empresa" data-position="right"><span class="fa fa-user" aria-hidden="true"></span><span class="xn-text">Tipos de empresas</span></div>
                            </a>
                            <ul>
                                <li <?php if($controller == 'tipoempresa' && $action == 'add') echo 'class="active"' ?>><a href="/tipoempresa/add"><span class="fa fa-group"></span> Agregar tipo de empresa</a></li>
                                <li <?php if($controller == 'tipoempresa' && $action == 'list') echo 'class="active"' ?>><a href="/tipoempresa/list"><span class="fa fa-file-text-o" aria-hidden="true"></span> Listado</a></li>
                            </ul>
                        </li>
                <!-- DEFINE MORE SECTIONS -->
                </ul>
            </div>
        <!-- PAGE CONTENT -->
            <div class="page-content">
            <!-- X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                <!-- TOGGLE NAVIGATION -->
                    <li class="xn-icon-button">
                        <a href="javascript:void();" class="x-navigation-minimize">
                            <span class="fa  <?php echo $this->minimized ? 'fa-indent' : 'fa-dedent'  ?>"></span>
                        </a>
                    </li>     
                      <!-- < ?php if(in_array('admin_donations', $this->admin['rol_modules']) || in_array('admin_standarddonations', $this->admin['rol_modules']) || in_array('admin_patients', $this->admin['rol_modules'])) : ?> -->
                    <li class="xn-icon-button" style="margin-top:10px;">
                       <div data-step="2" data-intro="Acá podrás crear facturas, pedidos y clientes" data-position="right"><button type="button" class="btn btn-default"><span class="fa fa-plus" style="color:#337ab7;"></span><b>Crear</b></button></div>
                        <ul class="xn-drop-left xn-drop-white animated zoomIn">
                            <!-- < ?php if(in_array('admin_donations', $this->admin['rol_modules'])): ?> -->
                            <li><a href="/venta/add"><span class="fa fa-files-o"></span>Venta</a></li>
                            <!-- < ?php endif;if(in_array('admin_standarddonations', $this->admin['rol_modules'])): ?> -->
                            <li><a href="/pedido/add"><span class="fa fa-align-justify"></span>Pedido</a></li>
                            <!-- < ?php endif;if(in_array('admin_patients', $this->admin['rol_modules'])) : ?> -->
                            <li><a href="/cliente/add"><span class="fa fa-users"></span>Nuevo cliente</a></li> 
                            <!-- < ?php endif ?> -->
                        </ul>                        
                    </li>               
                    <!-- < ?php endif; ?>    -->
                <!-- LOGOUT -->

                    <li class="xn-icon-button pull-right last">
                        <a href="#"><span class="fa fa-power-off"></span></a>
                        <ul class="xn-drop-left animated zoomIn">
                            <li><a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span> Cerrar sesión</a></li>
                        </ul>                        
                    </li> 
                       <!-- TOUR -->
                    <li class="xn-icon-button pull-right" style="padding-top:10px;margin-right:20px;">
                        <button onclick="introJs().start();" class="btn btn-danger" data-step="1" data-intro="Bienvenido <?php echo $this->admin['first_name'] ?>! para comenzar con el tutorial hacé click en ‘Siguiente’. " data-position="bottom">Empezar tutorial</button>
                    </li>
                    <!-- END TOUR -->
                </ul>
            <!-- ERROR MESSAGE -->
                <?php if($this->message['status'] == 'error'): ?>
                <div class="message-box-admin">
                    <div class="">
                        <div class="alert alert-danger">
                            <i class="fa fa-exclamation-triangle"></i> <?php echo $this->message['msg'] ?>
                        </div>
                    </div>
                </div>
                <?php endif; ?>
            <!-- SUCCESS MESSAGE -->
                <?php if($this->message['status'] == 'success'): ?>
                <div class="message-box-admin">
                    <div class="">
                        <div class="alert alert-success">
                            <i class="fa fa-info-circle"></i> <?php echo $this->message['msg'] ?>
                        </div>
                    </div>
                </div>
                <?php endif; ?>
            <!-- DINAMIC CONTENT -->
                <?php echo $this->layout()->content; ?>
            </div>
        <!-- LOGOUT MESSAGE -->
            <div class="message-box animated fadeIn" id="mb-signout">
                <div class="mb-container">
                    <div class="mb-middle">
                        <div class="mb-title"><span class="fa fa-sign-out"></span> Desea <strong>cerrar sesión</strong> ?</div>
                        
                        <div class="mb-footer">
                            <div class="pull-right">
                                <a href="/index/logout" class="btn btn-success btn-lg">Si</a>
                                <button class="btn btn-default btn-lg mb-control-close">No</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        <!-- MODAL NOTIFICATION -->
          <div id="modalNotification" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Request update</h4>
                    </div>
                    <div class="modal-body">
                        <p id="notificationText"></p>
                    </div>
                    <div class="modal-footer">
                      <button class="btn btn-primary btn-close" data-dismiss="modal">Cerrar</button>
                      <button class="btn btn-primary btn-requestsList" onclick="window.location.href='/'">Request List</button>
                    </div>
                </div>
            </div>
          </div>

          <script>
                $(document).ready(function() {
                    $('#modalNotification').on('hidden.bs.modal', function(){
                        if(whereAmI.controller === "index" && whereAmI.action === "index") {
                            location.reload();
                        };
                    });
                });
          </script>
    </body>
</html>