<?php         
$this->title = "Agregar nueva lista de precios";
$this->headTitle($this->title);
?>
<!-- BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="/">Panel Principal</a></li>
        <li><a href="/user/list">Producto</a></li>
        <li class="active">Nuevo</li>
    </ul>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-sm-12">
        <!-- ADD FORM -->
            <form id="add-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Nueva</strong> Lista de Precios</h3>
                        <ul class="panel-controls">
                        </ul>
                    </div>

                    <div class="panel-body">
                        <div class="form-group" id="form-group-marca" >
                            <label class="col-sm-3 col-xs-12 control-label">Tipo de cliente</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-suitcase"></span></span>
                                    <select name="tipo_cliente" id="tipo_cliente" type="text" class="form-control select">
                                        <option value="">Selecciona tipo de cliente</option>
                                        <?php
                                           foreach ($this->listadoTipoCliente as $key => $tipo_cliente): ?>
                                                <option <?php echo $this->data['tipo_cliente'] == $tipo_cliente['id'] ? "selected" : '' ; ?> value=<?php echo  $tipo_cliente['id'] ?>><?php echo $tipo_cliente['nombre']?></option>
                                            
                                        <?php endforeach; ?>
                                    </select>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Nombre</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="nombre" id="nombre" type="text" class="form-control"/>
                                </div> 
                            </div>
                        </div>

                        <div class="form-group">                                        
                            <label class="col-md-3 col-xs-12 control-label">Fecha vigencia</label>
                            <div class="col-md-6 col-xs-12">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                    <input name="fecha_vigencia" id="fecha_vigencia" type="text" class="form-control datepicker" />
                                </div>            
                            </div>
                        </div>

                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-default" type="button" onclick="history.back()">Volver</button>
                        <button class="btn btn-primary pull-right">Guardar</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datepicker.js"></script> 
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-select.js"></script>   
<script type=“text/javascript” src=“/js/plugins/jquery-validation/jquery.validate.js”></script>

<!-- END THIS PAGE PLUGINS -->

<script>
     $('.datepicker').datepicker({
    format: 'dd-mm-yyyy',
    // startDate: '-3d'
    language: 'es'
    });

var validator;
$().ready(function() {
    validator = $("#add-form").validate({
        ignore: '',
        rules: {
            nombre: {
                required: true
            },
            tipo_cliente: {
                required: true,
            },
            fecha_vigencia: "required"
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        messages: {
            nombre: {
                required: "Campo requerido",
            },
            fecha_vigencia: {
                required: "Campo requerido"
            },
            tipo_cliente: {
                required: "Campo requerido"
            }

        }
    });
});

</script>