<?php         
$this->title = "Editar usuario";
$this->headTitle($this->title);
?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Panel Principal</a></li>
    <li><a href="/producto/list">Producto</a></li>
    <li class="active">Editar</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <div class="row">
        <div class="col-sm-12">
        <!-- EDIT FORM -->
            <form id="edit-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Editar</strong> Producto original</h3>
                    </div>

                    <div class="panel-body">
                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Código</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="id_producto_original" type="text" class="form-control" value="<?php echo $this->data['id_producto_original'] ?>"/>
                                </div>                                            
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Descripción</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="descripcion" type="text" class="form-control" value="<?php echo $this->data['descripcion'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-default" type="button" onclick="history.back()">Volver</button>
                        <button class="btn btn-primary pull-right">Guardar</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datepicker.js"></script> 
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-select.js"></script>   
<script type=“text/javascript” src=“/js/plugins/jquery-validation/jquery.validate.js”></script>
<!-- END THIS PAGE PLUGINS -->

<script>
$().ready(function() {

    $("#add-form").validate({
        ignore: '',
        rules: {
            id_producto_original: "required",
            descripcion: "required"
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        messages: {

            descripcion: {
                required: "Campo requerido"
            },
            id_producto_original: {
                required: "Campo requerido"
            }
        }
    });
});
</script>