<?php         
$this->title = "Editar usuario";
$this->headTitle($this->title);
?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Panel Principal</a></li>
    <li><a href="/producto/list">Producto</a></li>
    <li class="active">Editar</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <div class="row">
        <div class="col-sm-12">
        <!-- EDIT FORM -->
            <form id="edit-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Editar</strong> Producto</h3>
                    </div>

                    <div class="panel-body">
                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Código</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="codigo" type="text" class="form-control" value="<?php echo $this->data['codigo'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Nombre</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="nombre" type="text" class="form-control" value="<?php echo $this->data['nombre'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Descripción</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="descripcion" type="text" class="form-control" value="<?php echo $this->data['descripcion'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Punto de pedido</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="punto_pedido" id="punto_pedido" type="text" class="form-control" value="<?php echo $this->data['punto_pedido'] ?>"/>
                                </div>
                            </div>
                        </div>

                        <!-- <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Cantidad</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="cantidad" id="cantidad" type="number" class="form-control" value="<?php echo $this->data['cantidad'] ?>"/>
                                </div>
                            </div>
                        </div>
 -->
                        <div class="form-group" id="form-group-marca" >
                            <label class="col-sm-3 col-xs-12 control-label">Marca</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-suitcase"></span></span>
                                    <select name="id_marca" id="id_marca" type="text" class="form-control select">
                                        <option value="">Selecciona Marca</option>
                                        <?php 
                                           foreach ($this->listadoMarcas as $key => $marca): ?>
                                                <option <?php echo $this->data['id_marca'] == $marca['id'] ? "selected" : '' ; ?> value=<?php echo  $marca['id'] ?>><?php echo $marca['nombre']?></option>
                                            
                                        <?php endforeach; ?>
                                    </select>
                                </div> 
                            </div>
                        </div>
                        <div class="form-group" id="form-group-original" >
                            <label class="col-sm-3 col-xs-12 control-label">Códigos originales</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-suitcase"></span></span>

                                    <select name="id_original[]" id="id_original" type="text" class="form-control select" data-live-search="true" multiple title="Selecciona el/los nros originales">
                                        <?php 
                                           foreach ($this->listadoOriginal as $key => $original): 
                                            foreach ($this->listadoEquivalente as $key => $equivalente): ?>
                                                <option <?php echo $original['id_producto_original'] == $equivalente['id_original'] ? "selected" : '' ; ?><?php endforeach; ?> value=<?php echo $original['id_producto_original'] ?>><?php echo $original['id_producto_original']?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div> 
                            </div>
                        </div>



                        <div class="text-center" id="user_image">
                            <img src="<?php echo $this->data['imagen_url'] ?>" class="img-thumbnail" width="200px">
                            <span class="help-block">Imagen actual</span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Imagen</label>
                            <div class="col-sm-6 col-xs-12">               
                                <input name="imagen_url" type="file" class="fileinput btn-primary" title="Browse file"/>
                            </div>
                        </div>

                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-default" type="button" onclick="history.back()">Volver</button>
                        <button class="btn btn-primary pull-right">Guardar</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-datepicker.js"></script> 
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-select.js"></script>   
<script type=“text/javascript” src=“/js/plugins/jquery-validation/jquery.validate.js”></script>
<!-- END THIS PAGE PLUGINS -->

<script>
$().ready(function() {

    $("#add-form").validate({
        ignore: '',
        rules: {
            nombre: "required",
            descripcion: "required",
            id_marca: "required",
            punto_pedido: "required"
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        messages: {

            imagen_url: {
                required: "Campo requerido"
            },
            descripcion: {
                required: "Campo requerido"
            },
            id_marca: {
                required: "Campo requerido"
            },
            nombre: {
                required: "Campo requerido"
            },
            punto_pedido: {
                required: "Campo requerido"
            }
        }
    });
});
</script>