<div class="table-responsive">
            <?php foreach ($this->listadoEquivalentes as $equivalente): ?>

                <?php echo $equivalente ?></br>
            <?php endforeach; ?>
</div>

<script>
    $(document).ready(function(){
        var table = $(".datatable-credits").DataTable({
              "order": [[0 , "desc" ]],
              "language":{
                  url : "/admin-public/js/plugins/datatables/Spanish.json"
              }                
          });
        table.draw();
    });
</script>

<script type="text/javascript" src="/admin-public/js/plugins/datatables/datatables.min.js"></script>          
<script type="text/javascript" src="/admin-public/js/plugins/datatables/dataTables.bootstrap.min.js"></script>
