<?php         
$this->title = "Edit administrator";
$this->headTitle($this->title);
?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Dashboard</a></li>
    <li><a href="/admin/list">Administrators</a></li>
    <li class="active">Edit</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <div class="row">
        <div class="col-sm-12">
        <!-- EDIT FORM -->
            <form id="edit-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Edit</strong> Administrator</h3>
                    </div>

                    <div class="panel-body">
                    
                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Fist name</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="first_name" type="text" class="form-control" value="<?php echo $this->data['first_name'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Last name</label>
                            <div class="col-sm-6 col-xs-12">                                            
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-list"></span></span>
                                    <input name="last_name" type="text" class="form-control" value="<?php echo $this->data['last_name'] ?>"/>
                                </div>                                            
                            </div>
                        </div>

                        <div class="text-center" id="user_image">
                            <img src="<?php echo $this->data['avatar_url'] ?>" class="img-thumbnail" width="200px">
                            <span class="help-block">Current avatar</span>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 col-xs-12 control-label">Avatar</label>
                            <div class="col-sm-6 col-xs-12">               
                                <input name="avatar_url" type="file" class="fileinput btn-primary" title="Browse file"/>
                            </div>
                        </div>

                        <div class="form-group">                                        
                            <label class="col-sm-3 col-xs-12 control-label">New password</label>
                            <div class="col-sm-6 col-xs-12">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-unlock-alt"></span></span>
                                    <input name="password" type="password" class="form-control"/>
                                </div>
                                <span class="help-block">Keep this field blank if you don't want to change your password</span>
                            </div>
                        </div>
                        
                    </div>
                    <div class="panel-footer">
                        <button class="btn btn-default" type="button" onclick="history.back()">Back</button>
                        <button class="btn btn-primary pull-right">Submit</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>                    
    
</div>
<!-- END PAGE CONTENT WRAPPER -->                                                


<!-- THIS PAGE PLUGINS -->
<script type="text/javascript" src="/admin-public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
<script type="text/javascript" src="/admin-public/js/jquery.validate.min.js"></script>
<!-- END THIS PAGE PLUGINS -->

<script>
$().ready(function() {

    $("#edit-form").validate({
        rules: {
            first_name: "required",
            last_name: "required",
            password: {
                minlength: 8
            }
        },
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        }
    });
});
</script>